### ISSUE TITLE
[Feature Request] Add support for Sonarqube 7.3

### ISSUE THREAD

**Issue by Kiran-B** [Backelite/sonar-swift#157]
SonarQube Community Edition **Version 7.3 (build 15553)** refuses to startup with **sonar-swift 0.3.7** installed. 
Following is the console output:

```
java.lang.IllegalStateException: Fail to load plugin Swift (Backelite) [backelitesonarswiftplugin]
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
        at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
        at org.sonar.server.platform.Platform.start(Platform.java:211)
        at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
        at org.sonar.server.platform.Platform.access$500(Platform.java:46)
        at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
        at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/Sensor
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        at org.sonar.plugins.swift.SwiftPlugin.getExtensions(SwiftPlugin.java:87)
        at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
        ... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.batch.Sensor
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        ... 25 common frames omitted

```

**Comment by Kiran-B** [comment]
This could be a duplicate of #155.
I reported this as a new one as #115 did not mention the version of Sonarqube and the plugin.

**Comment by egr-ext** [comment]
+1 very important for us

**Comment by NSAmit** [comment]
Looking for this fix immediately. Please fix this.

**Comment by FlyingTux123** [comment]
Grrr....I need that one too !!!

**Comment by NSAmit** [comment]
Any plans for this to be fixed. Any workaround to make sure it works with 7.3 version?

**Comment by egr-ext** [comment]
+1

**Comment by JaneZhang256** [comment]
+1 also do not support sonarqube 7.5

**Comment by mylonly** [comment]
+1

**Comment by huhood** [comment]
+1

**Comment by zippy1978** [comment]
Hi,

Finally !
It's done : https://github.com/Backelite/sonar-swift/releases/tag/0.4.3 

Gilles
