### ISSUE TITLE
SonarQube 7.4 is not loading the plugin

### ISSUE THREAD

**Issue by grevolution** [Backelite/sonar-swift#186]
SonarQube 7.4 is not loading the v0.4.2 plugin. I am getting following crash:

2018.11.06 22:56:16 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin Swift (Backelite) [backelitesonarswiftplugin]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$1$$Lambda$757/1145133089.run(Unknown Source)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/AbstractCpdMapping
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at com.backelite.sonarqube.swift.SwiftPlugin.getExtensions(SwiftPlugin.java:119)
	at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
	... 10 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.batch.AbstractCpdMapping
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 26 common frames omitted
2018.11.06 22:56:17 INFO  web[][o.s.p.StopWatcher] Stopping process

**Comment by dschaaff** [comment]
Seeing the same thing on our installation.

**Comment by schmidan** [comment]
SonarQube 7.4 would crash automatically stop each time i tried to start it including the sonar-swift plugin (no problems without the plugin thow)

i am using SonarQube 6.7.x LTS which seems to wirk with the plugin (assortment of warnings aside)

we would love to upgrade to a more recent version:
is there somewhere a documentation on what versions of host/plugin play nice together?

**Comment by Sura34** [comment]
I  am facing the same issue. Sonarqube 7.4 unable to start when there is a swift plugin. Anyone faced this issue and able to find a work around ?

**Comment by Madh93** [comment]
Same problem here. In SonarQube 7.1 works.

**Comment by Madh93** [comment]
Latest develop commit (https://github.com/Backelite/sonar-swift/commit/c6636d15977f973696b38eb6e5d49d131798b4ea) should be work.

To build the plugin:

```
git clone https://github.com/Backelite/sonar-swift
cd sonar-swift && git checkout c6636d1
mvn compile && mvn package
```

A `backelite-sonar-swift-plugin-0.4.3.jar` should be built under `sonar-swift-plugin/target/` directory.

[backelite-sonar-swift-plugin-0.4.3.tar.gz](https://github.com/Backelite/sonar-swift/files/2616047/backelite-sonar-swift-plugin-0.4.3.tar.gz)

**Comment by elsayed-atef** [comment]
@Madh93 I used your  attached jar files , but it gave me this error 
```
2018.12.06 11:36:25 ERROR web[][o.s.s.p.Platform] Web server startup failed
java.lang.IllegalStateException: Unable to read plugin manifest from jar : /opt/sonarqube/extensions/plugins/backelite-sonar-s                            wift-plugin-0.4.3.jar
        at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:125)
        at org.sonar.core.platform.PluginInfo.create(PluginInfo.java:395)
        at org.sonar.server.plugins.ServerPluginRepository.loadPreInstalledPlugins(ServerPluginRepository.java:135)
        at org.sonar.server.plugins.ServerPluginRepository.start(ServerPluginRepository.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
        at org.picocontainer.behaviors.Stored.start(Stored.java:110)
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
        at org.sonar.server.platform.platformlevel.PlatformLevel2.start(PlatformLevel2.java:113)
        at org.sonar.server.platform.Platform.start(Platform.java:211)
        at org.sonar.server.platform.Platform.startLevel2Container(Platform.java:177)
        at org.sonar.server.platform.Platform.init(Platform.java:87)
        at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java                            :45)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:120)
        ... 32 common frames omitted
2018.12.06 11:36:26 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2018.12.06 11:36:31 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2018.12.06 11:36:31 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
2018.12.06 11:36:31 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

```

**Comment by CveniEs** [comment]
I have the same error In sonarQube 7.4, the plugin is not support....
I don't want to use SonarQube 6.7.x LTS, can someone solve this problem ???????

**Comment by CveniEs** [comment]
@Madh93  I use the plugin you give, but it's only 10KB...


![image](https://user-images.githubusercontent.com/16501733/50502252-bb963180-0a98-11e9-8bb1-f0fddeb4407a.png)

**Comment by bcolvin** [comment]
4.3 works fine for me, be sure you're using the latest version. I can post the jar or you can build it from one of the PRs open or a fork. The AbstractCpd issue should be fixed with whatever release is on here currently as that was one of the last thing the maintainer of this project accepted

**Comment by zippy1978** [comment]
Hi,

Version 0.4.3 is now working ok on SonarQube 7.3 and above : https://github.com/Backelite/sonar-swift/releases/tag/0.4.3

Gilles

**Comment by sandeepbol** [comment]
I am still facing the same issue with release 0.4.4
