### ISSUE TITLE
SonarQube 7.5 is not loading the plugin

### ISSUE THREAD

**Issue by huhood** [Backelite/sonar-swift#195]
2019.01.06 23:45:53 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2019.01.06 23:45:54 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin Swift (Backelite) [backelitesonarswiftplugin]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/AbstractCpdMapping
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at com.backelite.sonarqube.swift.SwiftPlugin.getExtensions(SwiftPlugin.java:119)
	at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
	... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.batch.AbstractCpdMapping
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 25 common frames omitted
2019.01.06 23:45:54 INFO  web[][o.s.p.StopWatcher] Stopping process

**Comment by arthur657834** [comment]
same problem, anyone support ?

**Comment by antoine20001** [comment]
+1 
You should build the plugin 0.4.3 on develop branch

**Comment by antoine20001** [comment]
@bcolvin if CpdMapping was removed, how analyze the duplication code ?

**Comment by bcolvin** [comment]
@antoine20001 Wasn't able to figure that out, #188 references the issue (We can move discussion there). The last PR accepted here was primarily to fix a few issues related to the deprecation/removal of this class along with some others with sonarqube 7+ (see #155 , #157 , #167 ). For that PR I didn't upgrade the plugin version(was still 6.7), so perhaps you might to figure it out updating the plugin version to 7.5 if you have time.

**Comment by zippy1978** [comment]
Hi,

Version 0.4.3 is now working ok on SonarQube 7.3 and above : https://github.com/Backelite/sonar-swift/releases/tag/0.4.3

Gilles
