### ISSUE TITLE
SonarQube Server unable to started when sonar-swift-plugin-4.1.0.3087.jar plugin added

### ISSUE THREAD

**Issue by manojchandola** [Backelite/sonar-swift#199]
**Describe the bug**
I tried to use the latest "sonar-swift-plugin-4.1.0.3087.jar" plugin. But it does not start the SonarQube
server. If i remove that plugin it works smoothly, means server run and I am able to scan the source code.
So can you please help me out how to scan the iOS "objective-c & swift" source code. Because latest plugin is not working.

**To Reproduce**
1. Add "sonar-swift-plugin-4.1.0.3087.jar" plugin in the SonarQube extension folder
2. Shutdown the SonarQube Server and restart
3. Server unable to start
4. See error screenshot attached

**Expected behavior**
Server get start.

**Screenshots**
attached

**SonarQube environment:**
 - OS: MacOS Mojave 10.14.2
 - SonarQube-7.4

<img width="891" alt="51072189-addcd080-1682-11e9-9557-76174c1bf262" src="https://user-images.githubusercontent.com/5878848/51161762-b4a15880-18b9-11e9-855b-b05b92ffd44c.png">

**Comment by bcolvin** [comment]
I can't reproduce on my fork unfortunately

**Comment by manojchandola** [comment]
Please correct me if any steps goes wrong:
- downloaded the latest sonarqube-7.5
- run the server -> ~/bin/macosx-universal-64/sonar.sh console
- SonarQube server is up -> able to load http://localhost:9000 
- Now downloaded the latest swift plugin jar file sonar-swift-plugin-4.1.0.3087.jar
-  place swift plugin inside plugin folder ~/sonarqube-7.5/extensions/plugins/sonar-swift-plugin-4.1.0.3087.jar
- restart the Sonar Server
- SonarQube is unable to up -> always says SonarQube is stopped (above screenshot)

Please let me what i steps i need to follow, also provide me the link of sonar-swift plugin which will work at my end.

Thanks.

**Comment by salmojunior** [comment]
I'm facing the same issue with `backelite-sonar-swift-plugin-0.4.2.jar` version.

Environment details:
SonarQube 7.4
macOS 10.14.1 (18B75)

**Comment by oscarcv** [comment]
Running SonarQube 7.6 with version 4.1.0.387.jar

Crash on start:

```
java.lang.IllegalStateException: Fail to load plugin Swift (Backelite) [backelitesonarswiftplugin]
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
        at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:573)
        at org.sonar.server.platform.Platform.start(Platform.java:211)
        at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
        at org.sonar.server.platform.Platform.access$500(Platform.java:46)
        at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
        at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/AbstractCpdMapping
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        at com.backelite.sonarqube.swift.SwiftPlugin.getExtensions(SwiftPlugin.java:119)
        at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
        ... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.batch.AbstractCpdMapping
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        ... 25 common frames omitted
``` 

Image created with commandline:

``` 
docker run -d --name sonarqube \
    -p 9000:9000 \
    -v /path/to/extensions:/opt/sonarqube/extensions \
    sonarqube
```

**Comment by bcolvin** [comment]
@oscarcv there are many other issues referencing your stacktrace relating to AbstractCpdMapping (see #155 , #157 , #167 , #195). This issue on the other hand is one of the few recent ones that has nothing to do with it

**Comment by salmojunior** [comment]
I far as know backlite sonar-swift plugin works only with `LTS (Long-term Support): SonarQube 6.7.x` version. @manojchandola based on plugin name you've posted `sonar-swift-plugin-4.1.0.3087.jar`, it seems to be a official Sonar Swift plugin which will work only on Commercial versions, take a look: https://www.sonarsource.com/plans-and-pricing/

**Comment by manojchandola** [comment]
> I far as know backlite sonar-swift plugin works only with `LTS (Long-term Support): SonarQube 6.7.x` version. @manojchandola based on plugin name you've posted `sonar-swift-plugin-4.1.0.3087.jar`, it seems to be a official Sonar Swift plugin which will work only on Commercial versions, take a look: https://www.sonarsource.com/plans-and-pricing/

Thanks,
Can you please let me know if there is any free version for initial scan for iOS project? If it works well then we can go ahead for commercial version.

**Comment by salmojunior** [comment]
Just install latest LTS sonar version (sonarqube-6.7.6) and then download the latest plugin release: https://github.com/Backelite/sonar-swift/releases and follow the instructions from README file, it should work, this is the approach I'm using now! :)

**Comment by zippy1978** [comment]
Hi,

Version 0.4.3 is now working ok on SonarQube 7.3 and above : https://github.com/Backelite/sonar-swift/releases/tag/0.4.3

Gilles

**Comment by amarnathreddyg** [comment]
**Looks like this issue is reproducible in latest Sonarqube version(9.2). Any plans for the update ?**

Running SonarQube...
wrapper  | --> Wrapper Started as Console
wrapper  | Launching a JVM...
jvm 1    | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
jvm 1    |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
jvm 1    | 
jvm 1    | 2022.01.18 13:53:45 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /Applications/SonarQube/temp
jvm 1    | 2022.01.18 13:53:45 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: 127.0.0.1:9001, TCP: 127.0.0.1:53751]
jvm 1    | 2022.01.18 13:53:45 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/Applications/SonarQube/elasticsearch]: /Applications/SonarQube/elasticsearch/bin/elasticsearch
jvm 1    | 2022.01.18 13:53:45 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
jvm 1    | 2022.01.18 13:54:01 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
jvm 1    | 2022.01.18 13:54:01 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/Applications/SonarQube]: /Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/Applications/SonarQube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED -Dcom.redhat.fips=false -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/sonar-application-9.2.4.50792.jar:/Applications/SonarQube/lib/jdbc/h2/h2-1.4.199.jar org.sonar.server.app.WebServer /Applications/SonarQube/temp/sq-process18409264013982765350properties
jvm 1    | WARNING: A terminally deprecated method in java.lang.System has been called
jvm 1    | WARNING: System::setSecurityManager has been called by org.sonar.process.PluginSecurityManager (file:/Applications/SonarQube/lib/sonar-application-9.2.4.50792.jar)
jvm 1    | WARNING: Please consider reporting this to the maintainers of org.sonar.process.PluginSecurityManager
jvm 1    | WARNING: System::setSecurityManager will be removed in a future release
jvm 1    | 2022.01.18 13:54:07 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
jvm 1    | 2022.01.18 13:54:08 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143
jvm 1    | 2022.01.18 13:54:08 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
jvm 1    | 2022.01.18 13:54:08 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
wrapper  | <-- Wrapper Stopped
