### ISSUE TITLE
Metric 'files' should not be computed by a sensor

### ISSUE THREAD

**Issue by LiohAu** [Backelite/sonar-swift#212]
**Describe the bug**
When running run-sonar-swift.sh, I get an error during the sonar-runner phase.
If I run the sonar-runner alone (with -X option), I get the following java call stack.
I guess the plugin is not compatible with SonarQube 7.7, but maybe it is only the `saveMeasures` of SwiftSquidSensor to update ?

**Screenshots**
```
15:23:31.805 ERROR: Error during SonarQube Scanner execution
java.lang.UnsupportedOperationException: Metric 'files' should not be computed by a Sensor
	at org.sonar.scanner.sensor.DefaultSensorStorage.saveMeasure(DefaultSensorStorage.java:168)
	at org.sonar.scanner.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:132)
	at org.sonar.api.batch.sensor.measure.internal.DefaultMeasure.doSave(DefaultMeasure.java:95)
	at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
	at com.backelite.sonarqube.commons.MeasureUtil.saveMeasure(MeasureUtil.java:34)
	at com.backelite.sonarqube.swift.SwiftSquidSensor.saveMeasures(SwiftSquidSensor.java:85)
	at com.backelite.sonarqube.swift.SwiftSquidSensor.save(SwiftSquidSensor.java:79)
	at com.backelite.sonarqube.swift.SwiftSquidSensor.execute(SwiftSquidSensor.java:141)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:359)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:354)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:317)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:128)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

**SonarQube environment:**
 - OS: MacOS
 - Version : 7.7
 - Sonar-Scanner v3.3.0.1492

**Comment by AnarH93** [comment]
same problem there
`INFO: SonarQube Scanner 3.3.0.1492
INFO: Java 11.0.2 Oracle Corporation (64-bit)
INFO: Mac OS X 10.14.3 x86_64`
hope for sooner update

**Comment by meyyappanv** [comment]
Same issue here

INFO: SonarQube Scanner 3.2.0.1227
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Linux 4.15.0-45-generic amd64
INFO: SonarQube server 7.7.0

**Comment by diep-crystal** [comment]
Same issue,
INFO: SonarQube Scanner 3.3.0.1492
INFO: Java 1.8.0_202 Oracle Corporation (64-bit)
INFO: Mac OS X 10.14.4 x86_64
INFO: SonarQube server 7.7.0

Hope having update soon

**Comment by giteshgawade** [comment]
Same Issue, hope to have an update soon..

INFO: SonarQube Scanner 3.3.0.1492
INFO: Java 1.8.0_201 Oracle Corporation (64-bit)
INFO: Mac OS X 10.13.6 x86_64
INFO: SonarQube server 7.7.0

**Comment by promlife** [comment]
Same Issue

INFO: SonarQube Scanner 3.3.0.1492
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Mac OS X 10.13.6 x86_64
INFO: SonarQube server 7.7.0

**Comment by jpiechowka** [comment]
I have the same issue

INFO: SonarQube Scanner 3.3.0.1492
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Mac OS X 10.14.4 x86_64
INFO: SonarQube server 7.7.0

**Comment by andre-bahia** [comment]
Same Issue here

INFO: SonarQube Scanner 3.3.0.1492
INFO: Java 1.8.0_181 Oracle Corporation (64-bit)
INFO: Mac OS X 10.13.6 x86_64
INFO: SonarQube server 7.4.0

**Comment by etby** [comment]
Same Issue here

INFO: SonarQube Scanner 3.3.0.1492
INFO: Java 1.8.0_202 Oracle Corporation (64-bit)
INFO: Mac OS X 10.14.4 x86_64
INFO: SonarQube server 7.7.0

**Comment by promlife** [comment]
we have soled the problem according to the Workaround replyed by jpiechowka

**Comment by promlife** [comment]
> I have the same issue
> 
> INFO: SonarQube Scanner 3.3.0.1492
> INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
> INFO: Mac OS X 10.14.4 x86_64
> INFO: SonarQube server 7.7.0
> 
> Workaround:
> Ok so the fastest way to get it working is to delete or comment out line with `SwiftMetric.FILES` in `SwiftSquidSensor.java` and `ObjectiveCMetric.FILES` in `ObjectiveCSquidSensor.java`. Then it is easy to build the jar file with `mvn clean install` and replace the old plugin in SonarQube plugins directory.

we have soled the problem according to the Workaround replyed by jpiechowka

**Comment by onmyway133** [comment]
Here's how to work around this issues, together with many other tips https://github.com/onmyway133/blog/issues/216

**Comment by paicolman** [comment]
Did the changes proposed by onmyway133 but get the same error...

**Comment by kaleemasadmughal** [comment]
Facing Same issue.
Running SonarQube using SonarQube Runner.ERROR: Error during SonarQube Scanner execution
ERROR: Metric 'files' should not be computed by a Sensor
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
ERROR - Command 'sonar-scanner ' failed with error code: 1

**Comment by ivelius** [comment]
Absolutely same here.
`14:24:35.089 ERROR: Error during SonarQube Scanner execution
java.lang.UnsupportedOperationException: Metric 'files' should not be computed by a Sensor
	at org.sonar.scanner.sensor.DefaultSensorStorage.saveMeasure(DefaultSensorStorage.java:168)
	at org.sonar.scanner.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:132)
	at org.sonar.api.batch.sensor.measure.internal.DefaultMeasure.doSave(DefaultMeasure.java:95)
	at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
	at com.backelite.sonarqube.commons.MeasureUtil.saveMeasure(MeasureUtil.java:34)
	at com.backelite.sonarqube.swift.SwiftSquidSensor.saveMeasures(SwiftSquidSensor.java:85)
	at com.backelite.sonarqube.swift.SwiftSquidSensor.save(SwiftSquidSensor.java:79)
	at com.backelite.sonarqube.swift.SwiftSquidSensor.execute(SwiftSquidSensor.java:141)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:359)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:354)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:317)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:128)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)`

**Comment by ivelius** [comment]
I have followed the suggestion from @jpiechowka and recompiled the source code of the plugin with the lines commented out. Now I get a new error :/
```15:52:25.671 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Line number must be strictly positive: 0
	at org.sonar.api.internal.google.common.base.Preconditions.checkState(Preconditions.java:197)
	at org.sonar.api.batch.sensor.coverage.internal.DefaultCoverage.validateLine(DefaultCoverage.java:94)
	at org.sonar.api.batch.sensor.coverage.internal.DefaultCoverage.lineHits(DefaultCoverage.java:81)
	at com.backelite.sonarqube.swift.coverage.CoberturaReportParser.collectFileData(CoberturaReportParser.java:109)
	at com.backelite.sonarqube.swift.coverage.CoberturaReportParser.collectClassMeasures(CoberturaReportParser.java:91)
	at com.backelite.sonarqube.swift.coverage.CoberturaReportParser.collectPackageMeasures(CoberturaReportParser.java:79)
	at com.backelite.sonarqube.swift.coverage.CoberturaReportParser.parseReport(CoberturaReportParser.java:61)
	at com.backelite.sonarqube.swift.coverage.CoberturaSensor.execute(CoberturaSensor.java:69)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:359)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:354)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:317)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:128)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

**Comment by silverhammermba** [comment]
The patch worked for me. Note that you have to remove FILES **and** LINES metrics for **both** Swift and Objective-C. So **four** lines need to be removed.

**Comment by garyodonoghue** [comment]
@ivelius 
I think your issue with line numbers is more related to this i think:
https://github.com/cobertura/cobertura/issues/288

Removing those entries with number="0" in my cobertura report.xml file allowed me to upload to sonar, but i dont know why they're being generated in the first place :/

**Comment by kanakaraju043** [comment]
Same Issue here

INFO: sonar-scanner-4.0.0.1744-macosx
INFO: jdk-11.0.4_osx-x64_bin
INFO: Mac OS X 10.14.5 x86_64
INFO: sonarqube-7.9.1

**Comment by nascimentorafael** [comment]
Same isse here
INFO: sonar-scanner-cli-4.0.0.1744-macosx
INFO: 12.0.2, x86_64:	"Java SE 12.0.2"
INFO: Mac OS 10.14.5
INFO: sonarqube-developer-7.9.1

**Comment by umanglahane** [comment]
Facing same issue
INFO: Mac OS X 10.13.6
INFO: SonarQube 7.9.1
INFO: sonar-scanner-4.0.0.1744-macosx
INFO: Java 12.0.2

**Comment by nascimentorafael** [comment]
I could fix this issue with the workaround suggested here: https://dev.to/onmyway133/how-to-use-sonarqube-in-swift-projects-5db5

However, I get a different issue now:
```
ERROR: Error during SonarQube Scanner execution
java.lang.UnsupportedOperationException: Can not add the same measure twice on Source/XXXX/XXXX.swift: DefaultMeasure[component=Source/XXXX/XXXX.swift,metric=Metric[id=<null>,key=ncloc,description=Non commenting lines of code,type=INT,direction=-1,domain=Size,name=Lines of Code,qualitative=false,userManaged=false,enabled=true,worstValue=<null>,bestValue=<null>,optimizedBestValue=false,hidden=false,deleteHistoricalData=false,decimalScale=<null>],value=6,fromCore=false]
	at org.sonar.scanner.sensor.DefaultSensorStorage.saveMeasure(DefaultSensorStorage.java:172)
	at org.sonar.scanner.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:132)
	at org.sonar.api.batch.sensor.measure.internal.DefaultMeasure.doSave(DefaultMeasure.java:95)
	at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
	at com.backelite.sonarqube.commons.MeasureUtil.saveMeasure(MeasureUtil.java:34)
	at com.backelite.sonarqube.swift.SwiftSquidSensor.saveMeasures(SwiftSquidSensor.java:86)
	at com.backelite.sonarqube.swift.SwiftSquidSensor.save(SwiftSquidSensor.java:79)
	at com.backelite.sonarqube.swift.SwiftSquidSensor.execute(SwiftSquidSensor.java:140)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

Anyone knows what this is about?

**Comment by tyoc213** [comment]
> I have the same issue
> 
> INFO: SonarQube Scanner 3.3.0.1492
> INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
> INFO: Mac OS X 10.14.4 x86_64
> INFO: SonarQube server 7.7.0
> 
> Workaround:
> Ok so the fastest way to get it working is to delete or comment out line with `SwiftMetric.FILES` in `SwiftSquidSensor.java` and `ObjectiveCMetric.FILES` in `ObjectiveCSquidSensor.java`. Then it is easy to build the jar file with `mvn clean install` and replace the old plugin in SonarQube plugins directory.

what would be the correct way that maintainers would solve this?? so that it can be merged into master/dev and get a new official release that support current sonar?

**Comment by tyoc213** [comment]
Tracked to a change in 7.7 https://docs.sonarqube.org/latest/setup/upgrade-notes/#header-4

**Comment by gaelfoppolo** [comment]
https://github.com/Backelite/sonar-swift/pull/238 should fix this issue. Awaiting merge.

**Comment by tyoc213** [comment]
Nice, we will have a new release (specifiying incompatibility.. or we will just compile the version?)

**Comment by gaelfoppolo** [comment]
We have to discuss if we should embed this fix or not, regarding the incompatibility.
At the moment, I can't say if a new release will be issued soon.
If you need to fix, compile your own version, pending the release with this fix.

**Comment by kanakaraju043** [comment]
Can any one help with working sonar plugin by fixing below issue 
Metric 'files' should not be computed by a sensor

**Comment by gaelfoppolo** [comment]
New release embed this fix. Closing this issue.

**Comment by babusatti** [comment]
Getting same Metric files error...can i use this plugin in Linux? 

OS:linux
