### ISSUE TITLE
Multiple entries with same key: swift=Swift and swift=Swift

### ISSUE THREAD

**Issue by LiohAu** [Backelite/sonar-swift#214]
**Describe the bug**

When using the official and backelite plugins, sonar throw the following exception : 

```
java.lang.IllegalArgumentException: Multiple entries with same key: swift=Swift and swift=Swift
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
	at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1166)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140)
	at org.sonar.ce.task.projectanalysis.language.LanguageRepositoryImpl.<init>(LanguageRepositoryImpl.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
```

I think the Swift.java should not pass "Swift" as parameter in the following call but I don't really know the Sonar API, so I may be wrong : 
`super(KEY, "Swift");`

**To Reproduce**
Install Sonar with official Swift plugin + backelite swift plugin.

**Expected behavior**
The two plugins are combining their features (swiftlint for official one + lizard and other tools for the backelite one)

**SonarQube environment:**
 - OS: MacOS
 - Version 7.7

**Comment by gaelfoppolo** [comment]
This looks like a SonarQube issue, not an issue on the plugin itself.

**Comment by gaelfoppolo** [comment]
The official Swift plugin and this one use the same plugin key `swift'.` That means you can't use this plugin together with the official one. Same issues for with others unofficial plugin, such as Kotlin.
Closing this issue.
