### ISSUE TITLE
 String index out of range: -1 in lizard Report Parser

### ISSUE THREAD

**Issue by aramirezg1986** [Backelite/sonar-swift#217]
When I run the analysis, I get the following error: 
	at java.lang.String.substring(String.java:1967)
	at com.backelite.sonarqube.swift.complexity.LizardReportParser$SwiftFunction.<init>(LizardReportParser.java:180)
	at com.backelite.sonarqube.swift.complexity.LizardReportParser.parseMeasure(LizardReportParser.java:120)
	at com.backelite.sonarqube.swift.complexity.LizardReportParser.parseFile(LizardReportParser.java:88)
	at com.backelite.sonarqube.swift.complexity.LizardReportParser.parseReport(LizardReportParser.java:68)
	at com.backelite.sonarqube.swift.complexity.LizardSensor.execute(LizardSensor.java:63)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:408)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:403)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:360)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:126)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Comment by MediaComputing** [comment]
Get this error, too. Tried Lizard 1.14 and 1.16. MacOS. sonar-swift 0.4.4. 
Obviously it is trying to parse some bracket but does not seem to find one.

**Comment by egr-ext** [comment]
Same issue here, any solutions ? How can I find the missing bracket in the lizard-report.xml ?

**Comment by Cliff2103** [comment]
Same issue here. Didn't find any solution yet :(

**Comment by wg8** [comment]
Same issue here.

**Comment by egr-ext** [comment]
It does not support Objective C method with spaces in the signature in fact. 
I removed the Lizard analysis. 
Anyway OClint provides cyclomatic complexity metrics.

**Comment by iSofTom** [comment]
Same here. Any news on that subject ?

**Comment by rrolland** [comment]
Same issue and I didn't find any solution.

**Comment by JerryWolsen** [comment]
I found a work around to solve this:  remove all spaces in OC method after ':'  in lizard-report.xml before you start scanning the project using sonar-scanner. 

To be specific,  run  _sed -i "" "s/: /:/g" lizard-report.xml_  after report is generated.

It works for me.

**Comment by iSofTom** [comment]
Doesn't work for me :'(

**Comment by malikubaid** [comment]
Tried removing lizard analysis and also tried following command for spaces:
sed -i "" "s/: /:/g" sonar-reports/lizard-report.xml
Doesn't work for me.

Any other solution?

**Comment by hgshdt** [comment]
It may be solved by the following
https://github.com/Backelite/sonar-swift/issues/208#issuecomment-514009125

**Comment by gaelfoppolo** [comment]
Does https://github.com/Backelite/sonar-swift/issues/208#issuecomment-514009125 solves the issue?
Without response, this thread will be closed.

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
