### ISSUE TITLE
Error processing file named reports/cobertura.xml

### ISSUE THREAD

**Issue by cah-venkatachalapathy-dh** [Backelite/sonar-swift#224]
**Describe the bug**

I have been trying to do a sonar scan post collection of metrics as recommended using [fastlane](https://github.com/Backelite/sonar-swift/blob/develop/docs/sonarqube-fastlane.md) and have been facing the below error during fastlane sonar scan only. I understand that the error occurs due to firewall within the company's network which prevents it from calling http://cobertura.sourceforge.net/xml/coverage-04.dtd

The whole scan process is succesfull but the scan information is not being processed because of this. I was able to successfully scan the reports from a public internet and works fine though.

Could someone please recommend to overcome this, given that whitelisting is not an option?

```
[11:35:30]: ▸ INFO: Sensor Surefire [backelitesonarswiftplugin] (done) | time=3ms
[11:35:30]: ▸ INFO: Sensor Cobertura [backelitesonarswiftplugin]
[11:35:30]: ▸ INFO: Processing Cobertura report reports/cobertura.xml
[11:35:31]: ▸ ERROR: Error processing file named reports/cobertura.xml

[11:35:31]: ▸ java.io.IOException: Server returned HTTP response code: 503 for URL: http://cobertura.sourceforge.net/xml/coverage-04.dtd
[11:35:31]: ▸ at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
[11:35:31]: ▸ at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[11:35:31]: ▸ at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647)
[11:35:31]: ▸ at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1304)
[11:35:31]: ▸ at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1270)
[11:35:31]: ▸ at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:264)
[11:35:31]: ▸ at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1161)
[11:35:31]: ▸ at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1045)
[11:35:31]: ▸ at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:959)
[11:35:31]: ▸ at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
[11:35:31]: ▸ at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
[11:35:31]: ▸ at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
[11:35:31]: ▸ at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
[11:35:31]: ▸ at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
[11:35:31]: ▸ at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
[11:35:31]: ▸ at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
[11:35:31]: ▸ at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
[11:35:31]: ▸ at com.backelite.sonarqube.swift.coverage.CoberturaReportParser.parseReport(CoberturaReportParser.java:60)
[11:35:31]: ▸ at com.backelite.sonarqube.swift.coverage.CoberturaSensor.execute(CoberturaSensor.java:69)
[11:35:31]: ▸ at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:45)
[11:35:31]: ▸ at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:88)
[11:35:31]: ▸ at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:62)
[11:35:31]: ▸ at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:74)
[11:35:31]: ▸ at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:164)
[11:35:31]: ▸ at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
[11:35:31]: ▸ at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
[11:35:31]: ▸ at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:319)
[11:35:31]: ▸ at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:314)
[11:35:31]: ▸ at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:288)
[11:35:31]: ▸ at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
[11:35:31]: ▸ at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
[11:35:31]: ▸ at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
[11:35:31]: ▸ at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:82)
[11:35:31]: ▸ at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
[11:35:31]: ▸ at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
[11:35:31]: ▸ at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:131)
[11:35:31]: ▸ at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
[11:35:31]: ▸ at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
[11:35:31]: ▸ at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
[11:35:31]: ▸ at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:35:31]: ▸ at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:35:31]: ▸ at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:35:31]: ▸ at java.lang.reflect.Method.invoke(Method.java:498)
[11:35:31]: ▸ at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[11:35:31]: ▸ at com.sun.proxy.$Proxy0.execute(Unknown Source)
[11:35:31]: ▸ at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
[11:35:31]: ▸ at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
[11:35:31]: ▸ at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
[11:35:31]: ▸ at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
[11:35:31]: ▸ at org.sonarsource.scanner.cli.Main.main(Main.java:61)

[11:35:31]: ▸ INFO: Sensor Cobertura [backelitesonarswiftplugin] (done) | time=971ms
[11:35:31]: ▸ INFO: Sensor Lizard [backelitesonarswiftplugin]
```
**SonarQube environment:**

Sonarqube version 7.4

**Comment by gaelfoppolo** [comment]
This is not an issue related to our plugin.
The website was down at the moment you try to use it. An HTTP response code of 503 means "Service Unavailable". 
Closing the issue.

**Comment by cah-venkatachalapathy-dh** [comment]
@gaelfoppolo  the link was never down when i used it. Just reiterating "I was able to successfully scan the reports from a public internet and works fine though." When i try to do that from private/fire-walled network it just doesn't download since soundforge is blocked.. im looking for a way to privately access the file (without downloading) to make it succeed, is there a way if so can you please provide an alternate fix?

**Comment by NishantShukla001** [comment]
@cah-venkatachalapathy-dh
Did you able to resolve the issue ? 
If yes, please share details.
