### ISSUE TITLE
Swiftlint report ignored 

### ISSUE THREAD

**Issue by Jaff** [Backelite/sonar-swift#274]
### New Issue Checklist

- [x] Updated the plugin to the latest version 
- [x] I read the [Contribution Guidelines](https://github.com/Backelite/sonar-swift/blob/master/CONTRIBUTING.md)
- [x] I read the [documentation](https://github.com/Backelite/sonar-swift/wiki)
- [x] I searched for existing [GitHub issues](https://github.com/Backelite/sonar-swift/issues)

### Issue Description
Sonar is not providing detailed report from inputs.
##### Command executed
(in fastlane) sonar(sources_path: "./iOS", project_language: "swift", source_encoding: "UTF-8",
            sonar_runner_args: "#{ENV['SONAR_OPTIONS']}")
where:
```
SONAR_OPTIONS=-Dsonar.pullrequest.branch=sonarqube  -Dsonar.pullrequest.base=master -Dsonar.pullrequest.key=252
```
##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
[11:08:18]:
[11:08:18]: -------------------
[11:08:18]: --- Step: sonar ---
[11:08:18]: -------------------
[11:08:18]: ▸ INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/4.4.0.2170/libexec/conf/sonar-scanner.properties
[11:08:18]: ▸ INFO: Project root configuration file: /System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/sonar-project.properties
[11:08:18]: ▸ INFO: SonarScanner 4.4.0.2170
[11:08:18]: ▸ INFO: Java 1.8.0_191 Oracle Corporation (64-bit)
[11:08:18]: ▸ INFO: Mac OS X 10.15.5 x86_64
[11:08:19]: ▸ INFO: User cache: /Users/build/.sonar/cache
[11:08:19]: ▸ INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/4.4.0.2170/libexec/conf/sonar-scanner.properties
[11:08:19]: ▸ INFO: Project root configuration file: /System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/sonar-project.properties
[11:08:19]: ▸ INFO: Analyzing on SonarQube server 8.4.2
[11:08:19]: ▸ INFO: Default locale: "en_US", source code encoding: "UTF-8"
[11:08:19]: ▸ WARN: SonarScanner will require Java 11 to run starting in SonarQube 8.x
[11:08:19]: ▸ INFO: Load global settings
[11:08:20]: ▸ INFO: Load global settings (done) | time=264ms
[11:08:20]: ▸ INFO: Server id: 6CF5BE4F-AWRIk3VFrEe_XNA6vi10
[11:08:20]: ▸ INFO: User cache: /Users/build/.sonar/cache
[11:08:20]: ▸ INFO: Load/download plugins
[11:08:20]: ▸ INFO: Load plugins index
[11:08:20]: ▸ INFO: Load plugins index (done) | time=72ms
[11:08:20]: ▸ INFO: Load/download plugins (done) | time=140ms
[11:08:20]: ▸ INFO: Loaded core extensions: developer-scanner
[11:08:20]: ▸ INFO: Process project properties
[11:08:20]: ▸ INFO: Process project properties (done) | time=7ms
[11:08:20]: ▸ INFO: Execute project builders
[11:08:20]: ▸ INFO: Execute project builders (done) | time=4ms
[11:08:20]: ▸ INFO: Project key: company-stream-ios
[11:08:20]: ▸ INFO: Base dir: /System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source
[11:08:20]: ▸ INFO: Working dir: /System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/.scannerwork
[11:08:20]: ▸ INFO: Load project settings for component key: 'company-stream-ios'
[11:08:20]: ▸ INFO: Load project settings for component key: 'company-stream-ios' (done) | time=40ms
[11:08:21]: ▸ INFO: Load project branches
[11:08:21]: ▸ INFO: Load project branches (done) | time=46ms
[11:08:21]: ▸ INFO: Load project pull requests
[11:08:21]: ▸ INFO: Load project pull requests (done) | time=54ms
[11:08:21]: ▸ INFO: Load branch configuration
[11:08:21]: ▸ INFO: Found manual configuration of branch/PR analysis. Skipping automatic configuration.
[11:08:21]: ▸ INFO: Load branch configuration (done) | time=2ms
[11:08:21]: ▸ INFO: Load quality profiles
[11:08:21]: ▸ INFO: Load quality profiles (done) | time=75ms
[11:08:21]: ▸ INFO: Auto-configuring with CI 'Jenkins'
[11:08:21]: ▸ INFO: Load active rules
[11:08:22]: ▸ INFO: Load active rules (done) | time=1341ms
[11:08:22]: ▸ INFO: Pull request 252 for merge into master from sonarqube
[11:08:22]: ▸ INFO: SCM collecting changed files in the branch
[11:08:22]: ▸ INFO: SCM collecting changed files in the branch (done) | time=245ms
[11:08:22]: ▸ INFO: Indexing files...
[11:08:22]: ▸ INFO: Project configuration:
[11:08:24]: ▸ INFO: 561 files indexed
[11:08:24]: ▸ INFO: 0 files ignored because of scm ignore settings
[11:08:24]: ▸ INFO: Quality profile for swift: Sonar way
[11:08:24]: ▸ INFO: Quality profile for web: Sonar way
[11:08:24]: ▸ INFO: ------------- Run sensors on module "Proton iOS client"
[11:08:24]: ▸ INFO: Load metrics repository
[11:08:24]: ▸ INFO: Load metrics repository (done) | time=40ms
[11:08:25]: ▸ INFO: Sensor JavaXmlSensor [java]
[11:08:25]: ▸ INFO: Sensor JavaXmlSensor [java] (done) | time=3ms
[11:08:25]: ▸ INFO: Sensor HTML [web]
[11:08:25]: ▸ INFO: Sensor HTML [web] (done) | time=84ms
[11:08:25]: ▸ INFO: Sensor JaCoCo XML Report Importer [jacoco]
[11:08:25]: ▸ INFO: Importing 1 report(s). Turn your logs in debug mode in order to see the exhaustive list.
[11:08:25]: ▸ INFO: Sensor JaCoCo XML Report Importer [jacoco] (done) | time=31ms
[11:08:25]: ▸ INFO: Sensor SwiftLint [backelitesonarswiftplugin]
[11:08:25]: ▸ INFO: Processing SwiftLint report Reports/swiftlint.txt
[11:08:25]: ▸ INFO: Sensor SwiftLint [backelitesonarswiftplugin] (done) | time=290ms
[11:08:25]: ▸ INFO: Sensor Tailor [backelitesonarswiftplugin]
[11:08:25]: ▸ INFO: Sensor Tailor [backelitesonarswiftplugin] (done) | time=2ms
[11:08:25]: ▸ INFO: Sensor Swift Squid [backelitesonarswiftplugin]
[11:08:26]: ▸ WARN: Metric 'lines' is an internal metric computed by SonarQube/SonarCloud. Provided value is ignored.
[11:08:26]: ▸ INFO: Sensor Swift Squid [backelitesonarswiftplugin] (done) | time=369ms
[11:08:26]: ▸ INFO: Sensor Surefire [backelitesonarswiftplugin]
[11:08:26]: ▸ WARN: JUnit report directory not found at /System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/Reports/report.junit
[11:08:26]: ▸ INFO: Sensor Surefire [backelitesonarswiftplugin] (done) | time=1ms
[11:08:26]: ▸ INFO: Sensor Cobertura [backelitesonarswiftplugin]
[11:08:26]: ▸ INFO: Sensor Cobertura [backelitesonarswiftplugin] (done) | time=1ms
[11:08:26]: ▸ INFO: Sensor Lizard [backelitesonarswiftplugin]
[11:08:26]: ▸ INFO: Processing complexity report: /System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/Reports/lizard-report.xml
[11:08:26]: ▸ INFO: Sensor Lizard [backelitesonarswiftplugin] (done) | time=270ms
[11:08:26]: ▸ INFO: ------------- Run sensors on project
[11:08:26]: ▸ INFO: Sensor Zero Coverage Sensor
[11:08:26]: ▸ INFO: Sensor Zero Coverage Sensor (done) | time=5ms
[11:08:26]: ▸ INFO: CPD Executor Calculating CPD for 1 file
[11:08:26]: ▸ INFO: CPD Executor CPD calculation finished (done) | time=8ms
[11:08:26]: ▸ INFO: SCM writing changed lines
[11:08:26]: ▸ INFO: SCM writing changed lines (done) | time=2ms
[11:08:26]: ▸ INFO: Analysis report generated in 96ms, dir size=176 KB
[11:08:26]: ▸ INFO: Analysis report compressed in 217ms, zip size=131 KB
[11:08:27]: ▸ INFO: Analysis report uploaded in 159ms
[11:08:27]: ▸ INFO: ANALYSIS SUCCESSFUL, you can browse https://sonarqube.company.com/dashboard?id=company-stream-ios&pullRequest=252
[11:08:27]: ▸ INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
[11:08:27]: ▸ INFO: More about the report processing at https://sonarqube.company.com/api/ce/task?id=AXRu554RbW42HO9FIsLr
[11:08:27]: ▸ INFO: Analysis total time: 6.793 s
[11:08:27]: ▸ INFO: ------------------------------------------------------------------------
[11:08:27]: ▸ INFO: EXECUTION SUCCESS
[11:08:27]: ▸ INFO: ------------------------------------------------------------------------
[11:08:27]: ▸ INFO: Total time: 8.306s
[11:08:27]: ▸ INFO: Final Memory: 24M/549M
[11:08:27]: ▸ INFO: ------------------------------------------------------------------------
[11:08:27]: Cruising back to lane 'ios build_proton_app' 🚘

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    | setup_jenkins                                                 | 0           |
| 3    | set_info_plist_value                                          | 0           |
| 4    | set_info_plist_value                                          | 0           |
| 5    | set_info_plist_value                                          | 0           |
| 6    | set_info_plist_value                                          | 0           |
| 7    | set_info_plist_value                                          | 0           |
| 8    | get_info_plist_value                                          | 0           |
| 9    | update_project_provisioning                                   | 0           |
| 10   | update_project_team                                           | 0           |
| 11   | build_app                                                     | 253         |
| 12   | scan                                                          | 227         |
| 13   | Switch to ios metrics lane                                    | 0           |
| 14   | xcov                                                          | 6           |
| 15   | ../xccov-to-sonarqube-generic.sh ../Reports/action_0.xccovarc | 22          |
| 16   | lizard                                                        | 1           |
| 17   | swiftlint                                                     | 0           |
| 18   | sonar                                                         | 8           |
+------+---------------------------------------------------------------+-------------+

[11:08:27]: fastlane.tools just saved you 9 minutes! 🎉
</pre>
</details>

### Environment

sonar-project.properties file contains:
<details>
  <pre>
sonar.projectName="Proton iOS client"
sonar.projectKey=company-stream-ios
sonar.language=swift
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
sonar.sources=./iOS
sonar.host.url=https://sonarqube.company.com
sonar.login=989c0b621234b5148dfb4ce3b79fcfa3cb330c54
sonar.swift.project=Proton.xcodeproj
sonar.junit.reportsPath=Reports/
sonar.junit.include=*.junit
sonar.swift.lizard.report=Reports/lizard-report.xml
sonar.swift.swiftlint.report=Reports/swiftlint.txt
sonar.coverage.jacoco.xmlReportPaths=Reports/sonarqube-generic-coverage.xml
 </pre>
</details>

**Comment by Jaff** [comment]
<img width="1249" alt="xcov_report" src="https://user-images.githubusercontent.com/41868/92516548-37cb9c80-f1ca-11ea-8164-354e822be007.png">
<img width="1322" alt="Proton_report" src="https://user-images.githubusercontent.com/41868/92516564-3ac68d00-f1ca-11ea-99b4-e91adbcc11bc.png">

**Comment by Jaff** [comment]
Our most recent analysis failed lint; caused stack-trace from reading sonarlint.txt file:
```
[11:15:32]: ▸ INFO: Sensor Import of SwiftLint issues [swift]
[11:15:32]: ▸ INFO: Importing /System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/Reports/swiftlint.txt
[11:15:32]: ▸ ERROR: No issues information will be saved as the report file can't be read.
[11:15:32]: ▸ com.A.A.B: com.A.A.D.C: Expected value at line 1 column 1 path $
[11:15:32]: ▸ at com.A.A.K.A(Unknown Source)
[11:15:32]: ▸ at com.A.A.K.A(Unknown Source)
[11:15:32]: ▸ at com.sonar.swift.plugin.external.SwiftLintSensor.importReport(Unknown Source)
[11:15:32]: ▸ at com.sonar.swift.plugin.external.SwiftLintSensor.lambda$execute$1(Unknown Source)
[11:15:32]: ▸ at java.util.ArrayList.forEach(ArrayList.java:1257)
[11:15:32]: ▸ at com.sonar.swift.plugin.external.SwiftLintSensor.execute(Unknown Source)
[11:15:32]: ▸ at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
[11:15:32]: ▸ at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
[11:15:32]: ▸ at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
[11:15:32]: ▸ at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
[11:15:32]: ▸ at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
[11:15:32]: ▸ at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
[11:15:32]: ▸ at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
[11:15:32]: ▸ at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[11:15:32]: ▸ at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:393)
[11:15:32]: ▸ at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:389)
[11:15:32]: ▸ at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
[11:15:32]: ▸ at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
[11:15:32]: ▸ at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[11:15:32]: ▸ at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:144)
[11:15:32]: ▸ at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
[11:15:32]: ▸ at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[11:15:32]: ▸ at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
[11:15:32]: ▸ at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
[11:15:32]: ▸ at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
[11:15:32]: ▸ at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:15:32]: ▸ at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:15:32]: ▸ at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:15:32]: ▸ at java.lang.reflect.Method.invoke(Method.java:498)
[11:15:32]: ▸ at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[11:15:32]: ▸ at com.sun.proxy.$Proxy0.execute(Unknown Source)
[11:15:32]: ▸ at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
[11:15:32]: ▸ at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
[11:15:32]: ▸ at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
[11:15:32]: ▸ at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
[11:15:32]: ▸ at org.sonarsource.scanner.cli.Main.main(Main.java:61)
[11:15:32]: ▸ Caused by: com.A.A.D.C: Expected value at line 1 column 1 path $
[11:15:32]: ▸ at com.A.A.D.D.A(Unknown Source)
[11:15:32]: ▸ at com.A.A.D.D.E(Unknown Source)
[11:15:32]: ▸ at com.A.A.D.D.I(Unknown Source)
[11:15:32]: ▸ ... 36 common frames omitted
[11:15:32]: ▸ INFO: Sensor Import of SwiftLint issues [swift] (done) | time=3ms
```
The first few lines of the file contain:
```
/System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/iOS/DataManger/RequestInterceptor.swift:11:17: warning: Colon Violation: Colons should be next to the identifier when specifying a type and next to the key in dictionary literals. (colon)
/System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/iOS/DataManger/RequestInterceptor.swift:44:61: warning: Colon Violation: Colons should be next to the identifier when specifying a type and next to the key in dictionary literals. (colon)
/System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/iOS/DataManger/RequestInterceptor.swift:19:1: warning: Line Length Violation: Line should be 120 characters or less: currently 130 characters (line_length)
/System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/iOS/DataManger/RequestInterceptor.swift:24:1: warning: Line Length Violation: Line should be 120 characters or less: currently 130 characters (line_length)
/System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/iOS/DataManger/RequestInterceptor.swift:26:1: warning: Line Length Violation: Line should be 120 characters or less: currently 147 characters (line_length)
```

And prior to running sonar, the lint processing ended with:
```
[11:14:48]: ▸ Linting 'LauchHandler.swift' (415/415)
[11:14:48]: ▸ Done linting! Found 8538 violations, 636 serious in 415 files.
[11:14:48]: 
[11:14:48]: SwiftLint finished with exit code 0, which would normally fail the build.
[11:14:48]: fastlane will continue because the `ignore_exit_status` option was used! 🙈
[11:14:48]: 
```

**Comment by Jaff** [comment]
Updated sonarscanner to`4.5.0` and swiftlint to `0.41.0` but still seeing the crash reading swiftlint.txt:
```
[15:06:19]: ▸ Linting 'ErrorInfo.swift' (410/419)
[15:06:19]: ▸ Linting 'ErrorView.swift' (411/419)
[15:06:19]: ▸ Linting 'SlingUpsellSnackbarView.swift' (412/419)
[15:06:19]: ▸ Linting 'ProtonSpinner.swift' (413/419)
[15:06:19]: ▸ Linting 'GradientView.swift' (414/419)
[15:06:19]: ▸ Linting 'InsetTextfield.swift' (415/419)
[15:06:19]: ▸ Linting 'SlingAccountLinkingHelper.swift' (416/419)
[15:06:19]: ▸ Linting 'BaseListPresenter.swift' (417/419)
[15:06:19]: ▸ Linting 'BaseListItemPresenter.swift' (418/419)
[15:06:19]: ▸ Linting 'LauchHandler.swift' (419/419)
[15:06:19]: ▸ Done linting! Found 12876 violations, 663 serious in 419 files.
[15:06:19]: 
[15:06:19]: SwiftLint finished with exit code 0, which would normally fail the build.
[15:06:19]: fastlane will continue because the `ignore_exit_status` option was used! 🙈
[15:06:19]: 
[15:06:19]: -------------------
[15:06:19]: --- Step: sonar ---
[15:06:19]: -------------------
[15:06:19]: ▸ INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/4.5.0.2216/libexec/conf/sonar-scanner.properties
[15:06:19]: ▸ INFO: Project root configuration file: /System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/sonar-project.properties
[15:06:19]: ▸ INFO: SonarScanner 4.5.0.2216
[15:06:19]: ▸ INFO: Java 1.8.0_191 Oracle Corporation (64-bit)
[15:06:19]: ▸ INFO: Mac OS X 10.15.5 x86_64
[15:06:20]: ▸ INFO: User cache: /Users/build/.sonar/cache
[15:06:20]: ▸ INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/4.5.0.2216/libexec/conf/sonar-scanner.properties
[15:06:20]: ▸ INFO: Project root configuration file: /System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/sonar-project.properties
[15:06:20]: ▸ INFO: Analyzing on SonarQube server 8.5.1
[15:06:20]: ▸ INFO: Default locale: "en_US", source code encoding: "UTF-8"
[15:06:20]: ▸ WARN: SonarScanner will require Java 11 to run starting in SonarQube 8.x
[15:06:20]: ▸ INFO: Load global settings
[15:06:21]: ▸ INFO: Load global settings (done) | time=268ms
[15:06:21]: ▸ INFO: Server id: 6CF5BE4F-AWRIk3VFrEe_XNA6vi10
[15:06:21]: ▸ INFO: User cache: /Users/build/.sonar/cache
[15:06:21]: ▸ INFO: Load/download plugins
[15:06:21]: ▸ INFO: Load plugins index
[15:06:21]: ▸ INFO: Load plugins index (done) | time=75ms
[15:06:21]: ▸ INFO: Load/download plugins (done) | time=209ms
[15:06:21]: ▸ INFO: Loaded core extensions: developer-scanner
[15:06:22]: ▸ INFO: JavaScript/TypeScript frontend is enabled
[15:06:22]: ▸ INFO: Process project properties
[15:06:22]: ▸ INFO: Process project properties (done) | time=7ms
[15:06:22]: ▸ INFO: Execute project builders
[15:06:22]: ▸ INFO: Execute project builders (done) | time=1ms
[15:06:22]: ▸ INFO: Project key: tivo-stream-ios
[15:06:22]: ▸ INFO: Base dir: /System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source
[15:06:22]: ▸ INFO: Working dir: /System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/.scannerwork
[15:06:22]: ▸ INFO: Load project settings for component key: 'tivo-stream-ios'
[15:06:22]: ▸ INFO: Load project settings for component key: 'tivo-stream-ios' (done) | time=45ms
[15:06:22]: ▸ INFO: Load project branches
[15:06:22]: ▸ INFO: Load project branches (done) | time=43ms
[15:06:22]: ▸ INFO: Load project pull requests
[15:06:22]: ▸ INFO: Load project pull requests (done) | time=42ms
[15:06:22]: ▸ INFO: Load branch configuration
[15:06:22]: ▸ INFO: Found manual configuration of branch/PR analysis. Skipping automatic configuration.
[15:06:22]: ▸ INFO: Load branch configuration (done) | time=2ms
[15:06:22]: ▸ INFO: Load quality profiles
[15:06:22]: ▸ INFO: Load quality profiles (done) | time=130ms
[15:06:22]: ▸ INFO: Auto-configuring with CI 'Jenkins'
[15:06:22]: ▸ INFO: Load active rules
[15:06:24]: ▸ INFO: Load active rules (done) | time=1624ms
[15:06:24]: ▸ INFO: Branch name: PR-252
[15:06:24]: ▸ INFO: Indexing files...
[15:06:24]: ▸ INFO: Project configuration:
[15:06:26]: ▸ INFO: 780 files indexed
[15:06:26]: ▸ INFO: 0 files ignored because of scm ignore settings
[15:06:26]: ▸ INFO: Quality profile for swift: Sonar way
[15:06:26]: ▸ INFO: Quality profile for web: Sonar way
[15:06:26]: ▸ INFO: ------------- Run sensors on module "Proton iOS client"
[15:06:26]: ▸ INFO: JavaScript/TypeScript frontend is enabled
[15:06:26]: ▸ INFO: Load metrics repository
[15:06:26]: ▸ INFO: Load metrics repository (done) | time=40ms
[15:06:28]: ▸ INFO: Sensor CSS Rules [cssfamily]
[15:06:29]: ▸ WARN: CSS rules were not executed. Failed to parse Node.js version, got 'Couldn't find the Node.js binary. Ensure you have Node.js installed. Open an issue on https://github.com/sindresorhus/run-node'
[15:06:30]: ▸ INFO: Sensor CSS Rules [cssfamily] (done) | time=1960ms
[15:06:30]: ▸ INFO: Sensor C# Properties [csharp]
[15:06:30]: ▸ INFO: Sensor C# Properties [csharp] (done) | time=1ms
[15:06:30]: ▸ INFO: Sensor JavaXmlSensor [java]
[15:06:30]: ▸ INFO: Sensor JavaXmlSensor [java] (done) | time=4ms
[15:06:30]: ▸ INFO: Sensor HTML [web]
[15:06:30]: ▸ INFO: Load project repositories
[15:06:30]: ▸ INFO: Load project repositories (done) | time=72ms
[15:06:30]: ▸ INFO: Sensor HTML [web] (done) | time=170ms
[15:06:30]: ▸ INFO: Sensor VB.NET Properties [vbnet]
[15:06:30]: ▸ INFO: Sensor VB.NET Properties [vbnet] (done) | time=1ms
[15:06:30]: ▸ INFO: Sensor SonarSwift [swift]
[15:06:30]: ▸ INFO: 419 source files to be analyzed
[15:06:38]: ▸ INFO: 419/419 source files have been analyzed
[15:06:38]: ▸ INFO: Sensor SonarSwift [swift] (done) | time=8165ms
[15:06:38]: ▸ INFO: Sensor Import of SwiftLint issues [swift]
[15:06:38]: ▸ INFO: Importing /System/Volumes/Data/cde/hudson/workspace/iOS-Proton-fusion_PR-252/source/Reports/swiftlint.txt
[15:06:38]: ▸ ERROR: No issues information will be saved as the report file can't be read.
[15:06:38]: ▸ com.A.A.B: com.A.A.D.C: Expected value at line 1 column 1 path $
[15:06:38]: ▸ at com.A.A.K.A(Unknown Source)
[15:06:38]: ▸ at com.A.A.K.A(Unknown Source)
[15:06:38]: ▸ at com.sonar.swift.plugin.external.SwiftLintSensor.importReport(Unknown Source)
[15:06:38]: ▸ at com.sonar.swift.plugin.external.SwiftLintSensor.lambda$execute$1(Unknown Source)
[15:06:38]: ▸ at java.util.ArrayList.forEach(ArrayList.java:1257)
[15:06:38]: ▸ at com.sonar.swift.plugin.external.SwiftLintSensor.execute(Unknown Source)
[15:06:38]: ▸ at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
[15:06:38]: ▸ at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
[15:06:38]: ▸ at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
[15:06:38]: ▸ at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
[15:06:38]: ▸ at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
[15:06:38]: ▸ at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
[15:06:38]: ▸ at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
[15:06:38]: ▸ at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[15:06:38]: ▸ at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:393)
[15:06:38]: ▸ at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:389)
[15:06:38]: ▸ at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
[15:06:38]: ▸ at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
[15:06:38]: ▸ at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[15:06:38]: ▸ at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:144)
[15:06:38]: ▸ at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
[15:06:38]: ▸ at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[15:06:38]: ▸ at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
[15:06:38]: ▸ at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
[15:06:38]: ▸ at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
[15:06:38]: ▸ at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:06:38]: ▸ at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:06:38]: ▸ at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:06:38]: ▸ at java.lang.reflect.Method.invoke(Method.java:498)
[15:06:38]: ▸ at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[15:06:38]: ▸ at com.sun.proxy.$Proxy0.execute(Unknown Source)
[15:06:38]: ▸ at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
[15:06:38]: ▸ at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
[15:06:38]: ▸ at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
[15:06:38]: ▸ at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
[15:06:38]: ▸ at org.sonarsource.scanner.cli.Main.main(Main.java:61)
[15:06:38]: ▸ Caused by: com.A.A.D.C: Expected value at line 1 column 1 path $
[15:06:38]: ▸ at com.A.A.D.D.A(Unknown Source)
[15:06:38]: ▸ at com.A.A.D.D.E(Unknown Source)
[15:06:38]: ▸ at com.A.A.D.D.I(Unknown Source)
[15:06:38]: ▸ ... 36 common frames omitted
[15:06:38]: ▸ INFO: Sensor Import of SwiftLint issues [swift] (done) | time=4ms
```

**Comment by Jaff** [comment]
I have revised the project settings so that swiftlint writes xml; also setup slather to provide coverage report in compatible format. All reports are being read and show that status, yet I still see no results in SonarQube view.
