### ISSUE TITLE
Wrapper is stopped due to jdk error.

### ISSUE THREAD

**Issue by ragul-m46** [Backelite/sonar-swift#305]
### New Issue Checklist

- [ ] Updated the plugin to the latest version 
- [ ] I read the [Contribution Guidelines](https://github.com/Backelite/sonar-swift/blob/master/CONTRIBUTING.md)
- [ ] I read the [documentation](https://github.com/Backelite/sonar-swift/wiki)
- [x] I searched for existing [GitHub issues](https://github.com/Backelite/sonar-swift/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

Using Java version - 11

Running SonarQube...
wrapper  | --> Wrapper Started as Console
wrapper  | Launching a JVM...
jvm 1    | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
jvm 1    |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
jvm 1    | 
jvm 1    | 2022.07.18 13:39:27 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /Applications/SonarQube/temp
jvm 1    | 2022.07.18 13:39:27 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: 127.0.0.1:9001, TCP: 127.0.0.1:51887]
jvm 1    | 2022.07.18 13:39:27 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[ELASTICSEARCH] from [/Applications/SonarQube/elasticsearch]: /Applications/SonarQube/elasticsearch/bin/elasticsearch
jvm 1    | 2022.07.18 13:39:27 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
jvm 1    | 2022.07.18 13:39:45 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
jvm 1    | 2022.07.18 13:39:45 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[WEB_SERVER] from [/Applications/SonarQube]: /Library/Java/JavaVirtualMachines/jdk-11.0.15.1.jdk/Contents/Home/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/Applications/SonarQube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED -Dcom.redhat.fips=false -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/sonar-application-9.5.0.56709.jar:/Applications/SonarQube/lib/jdbc/h2/h2-2.1.210.jar org.sonar.server.app.WebServer /Applications/SonarQube/temp/sq-process10405468898462525718properties
jvm 1    | 2022.07.18 13:39:54 INFO  app[][o.s.a.SchedulerImpl] Process[Web Server] is stopped
jvm 1    | 2022.07.18 13:39:54 INFO  app[][o.s.a.SchedulerImpl] Process[ElasticSearch] is stopped
jvm 1    | 2022.07.18 13:39:54 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [ElasticSearch]: 143
jvm 1    | 2022.07.18 13:39:54 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
wrapper  | <-- Wrapper Stopped

**Comment by YogeshBhattGWL** [comment]
I am facing same issue in **MacM1 Pro**. I have tried with **Java 11 and Java 18.**

**Error:**

```
wrapper  | --> Wrapper Started as Console
wrapper  | Launching a JVM...
jvm 1    | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
jvm 1    |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
jvm 1    | 
jvm 1    | 
jvm 1    | WARNING - Unable to load the Wrapper's native library because none of the
jvm 1    |           following files:
jvm 1    |             libwrapper-macosx-aarch64-64.dylib
jvm 1    |             libwrapper-macosx-universal-64.dylib
jvm 1    |             libwrapper.dylib
jvm 1    |           could be located on the following java.library.path:
jvm 1    |             /Applications/SonarQube/bin/macosx-universal-64/./lib
jvm 1    |           Please see the documentation for the wrapper.java.library.path
jvm 1    |           configuration property.
jvm 1    |           System signals will not be handled correctly.
jvm 1    | 
jvm 1    | 2022.08.02 13:47:36 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /Applications/SonarQube/temp
jvm 1    | 2022.08.02 13:47:36 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: 127.0.0.1:9001, TCP: 127.0.0.1:54625]
jvm 1    | 2022.08.02 13:47:36 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[ELASTICSEARCH] from [/Applications/SonarQube/elasticsearch]: /Applications/SonarQube/elasticsearch/bin/elasticsearch
jvm 1    | 2022.08.02 13:47:36 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
jvm 1    | Exception in thread "main" java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
jvm 1    | 	at java.base/java.lang.System.setSecurityManager(System.java:416)
jvm 1    | 	at org.elasticsearch.bootstrap.Security.setSecurityManager(Security.java:99)
jvm 1    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:70)
jvm 1    | 2022.08.02 13:47:36 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [ElasticSearch]: 1
jvm 1    | 2022.08.02 13:47:36 INFO  app[][o.s.a.SchedulerImpl] Process[ElasticSearch] is stopped
jvm 1    | 2022.08.02 13:47:36 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
jvm 1    | 2022.08.02 13:47:37 ERROR app[][o.s.a.p.EsManagedProcess] Failed to check status
jvm 1    | org.elasticsearch.ElasticsearchException: java.lang.InterruptedException
jvm 1    | 	at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2695)
jvm 1    | 	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171)
jvm 1    | 	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137)
jvm 1    | 	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105)
jvm 1    | 	at org.elasticsearch.client.ClusterClient.health(ClusterClient.java:151)
jvm 1    | 	at org.sonar.application.es.EsConnectorImpl.getClusterHealthStatus(EsConnectorImpl.java:64)
jvm 1    | 	at org.sonar.application.process.EsManagedProcess.checkStatus(EsManagedProcess.java:92)
jvm 1    | 	at org.sonar.application.process.EsManagedProcess.checkOperational(EsManagedProcess.java:77)
jvm 1    | 	at org.sonar.application.process.EsManagedProcess.isOperational(EsManagedProcess.java:62)
jvm 1    | 	at org.sonar.application.process.ManagedProcessHandler.refreshState(ManagedProcessHandler.java:223)
jvm 1    | 	at org.sonar.application.process.ManagedProcessHandler$EventWatcher.run(ManagedProcessHandler.java:288)
jvm 1    | Caused by: java.lang.InterruptedException: null
jvm 1    | 	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
jvm 1    | 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:243)
jvm 1    | 	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:75)
jvm 1    | 	at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2692)
jvm 1    | 	... 10 common frames omitted
wrapper  | <-- Wrapper Stopped

```

**Comment by YogeshBhattGWL** [comment]
@ragul-m46 Did you get solution for this?

**Comment by YogeshBhattGWL** [comment]
SonarQube is not supported in Mac M1.

**Comment by ragul-m46** [comment]
Hi Yogesh,
      But mine is not a M1 chip, I use intel only...but still I am facing this issue..Haven't found a solution yet.

Thanks.

________________________________

**Comment by nhan7777** [comment]
I have the same issue with Intel Macbook also

**Comment by InfoSecPS** [comment]
I was using a newer version of OpenJDK, when it's OpenJDK version 17 you need.
