### ISSUE TITLE
java.lang.ClassNotFoundException: org.sonar.api.checks.AnnotationCheckFactory

### ISSUE THREAD

**Issue by giacgbj** [Backelite/sonar-swift#37]
sonar-swift 0.2.3, 0.2.4
SonarQube 6.0

```
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Unable to register extension org.sonar.plugins.swift.SwiftSquidSensor from plugin 'backelitesonarswiftplugin'
    at org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:248)
    at org.sonar.scanner.bootstrap.ExtensionInstaller.doInstall(ExtensionInstaller.java:76)
    at org.sonar.scanner.bootstrap.ExtensionInstaller.install(ExtensionInstaller.java:57)
    at org.sonar.scanner.scan.ModuleScanContainer.addExtensions(ModuleScanContainer.java:176)
    at org.sonar.scanner.scan.ModuleScanContainer.doBeforeStart(ModuleScanContainer.java:93)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:140)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
    at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
    at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
    at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
    at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
    at org.sonar.runner.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61)
    at com.sun.proxy.$Proxy0.execute(Unknown Source)
    at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:274)
    at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165)
    at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152)
    at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:118)
    at org.sonarsource.scanner.cli.Main.execute(Main.java:80)
    at org.sonarsource.scanner.cli.Main.main(Main.java:66)
Caused by: java.lang.NoClassDefFoundError: Lorg/sonar/api/checks/AnnotationCheckFactory;
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
    at java.lang.Class.getDeclaredFields(Class.java:1916)
    at org.picocontainer.injectors.AdaptingInjection$2.run(AdaptingInjection.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.picocontainer.injectors.AdaptingInjection.injectionFieldAnnotated(AdaptingInjection.java:209)
    at org.picocontainer.injectors.AdaptingInjection.fieldAnnotatedInjectionAdapter(AdaptingInjection.java:188)
    at org.picocontainer.injectors.AdaptingInjection.createComponentAdapter(AdaptingInjection.java:57)
    at org.picocontainer.behaviors.AbstractBehaviorFactory.createComponentAdapter(AbstractBehaviorFactory.java:44)
    at org.picocontainer.behaviors.OptInCaching.createComponentAdapter(OptInCaching.java:45)
    at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:536)
    at org.picocontainer.DefaultPicoContainer.access$300(DefaultPicoContainer.java:84)
    at org.picocontainer.DefaultPicoContainer$AsPropertiesPicoContainer.addComponent(DefaultPicoContainer.java:1149)
    at org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:246)
    ... 30 more
Caused by: java.lang.ClassNotFoundException: org.sonar.api.checks.AnnotationCheckFactory
    at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
    at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
    at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
    ... 44 more
```

**Comment by zippy1978** [comment]
Hi,

This is probably due to API deprecations in SonarQube 6.
I will have a look at it

**Comment by skromberg** [comment]
I've created a patch for version 2.4.0. But all in all its not possible to create a proper pull request for it. There are so much changes, most of the sensors are deprecated. The patch works fine with our sonar 6.0 and uses the new API in some cases. The results are identically to the current version.

**Comment by jazomand** [comment]
Hi @skromberg, maybe you could publish your patch? Or your patched plugin? It would help me a lot :)

**Comment by skromberg** [comment]
For sure - currently i polish the code and check the plugin in our multi-projekt sonar. After this i will publish the patch as branch. And additionally as jar, because the build chain (pom and shell script) is broken too.

**Comment by skromberg** [comment]
@jazomand @zippy1978 FYI: https://github.com/sprylab/sonar-swift/tree/feature/sonar_6_fix

**Comment by zippy1978** [comment]
Thanks a lot @skromberg !
Could you create a PR for the branch feat/sonarqube6 ?

**Comment by skromberg** [comment]
@zippy1978 i think it makes no sense - on the one hand is my branch more a workaround for 6.0. On the other hand the maven build chain is broken. From my perspective it is necessary to rewrite the whole plugin.

**Comment by jazomand** [comment]
Thank you so much!!!

**Comment by kumarSC** [comment]
Hey @zippy1978 , I ran into this issue as we updated out SonarQube to 6.0. Is this a blocking issue for using swift plugin with sonarqube6.0. 
@skromberg , are you still looking into this issue? in that case I will wait for your PR.

**Comment by zippy1978** [comment]
Hi,

I will probably have a look at it on next week.
It seems to be a big refactoring, and moving to 6.0 will probably stop 4.x support..

**Comment by Alex009** [comment]
Hi.
I fix SonarQube 6 support. See #40

**Comment by zippy1978** [comment]
Hi, 
@Alex009 work is merged on feat/sonarqube6 branch.

**Comment by aanjanhari** [comment]
I am still getting the same errors reported with code from feat/soanrqube6 branch.

**Comment by Alex009** [comment]
@aanjanhari are you restart sonar after install new version?
And try this compiled version
[backelite-sonar-swift-plugin-0.2.4.jar.zip](https://github.com/Backelite/sonar-swift/files/478073/backelite-sonar-swift-plugin-0.2.4.jar.zip)

**Comment by aanjanhari** [comment]
@Alex009 Thanks. This jar works.

**Comment by giacgbj** [comment]
@Alex009 I confirm it works too.

**Comment by mstrzele** [comment]
@zippy1978 is there anything that needs to be done before the next release with this patch included?

**Comment by pradeepgudipati** [comment]
Fixed for me too !! thanks @skromberg

**Comment by zippy1978** [comment]
@mstrzele 
Actually I wanted to re-test the pending PR (for better test support) and check for SwifLint upgrades compat first

**Comment by palusik86** [comment]
More people looking for this fix ;-)

**Comment by zippy1978** [comment]
Hi all,

I'm pleased to annonce that release 0.3.0 is out with SonarQube 6 support !

https://github.com/Backelite/sonar-swift/releases/tag/0.3.0
