### ISSUE TITLE
Caused by: The rule 'SwiftLint:legacy_constant' does not exist.

### ISSUE THREAD

**Issue by akshaysyaduvanshi** [Backelite/sonar-swift#4]
Getting above error while running sonar-runner
Used this command to create report swiftlint lint --path SourceCode/ > ./sonar-reports/swiftlint.txt

Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
	at org.sonar.runner.api.Runner.execute(Runner.java:100)
	at org.sonar.runner.Main.executeTask(Main.java:70)
	at org.sonar.runner.Main.execute(Main.java:59)
	at org.sonar.runner.Main.main(Main.java:53)

**Comment by akshaysyaduvanshi** [comment]
This error was occurring because i was using higher version of swiftlint.
