### ISSUE TITLE
Test failures lead to NullPointer exception

### ISSUE THREAD

**Issue by haynzz** [Backelite/sonar-swift#67]
Using sonarQube Version 5.6.5
sonarSwift 0.3.1

When the junit file contains this:

```
<?xml version='1.0' encoding='UTF-8'?>
<testsuites name='HotelSearchTests.xctest' tests='2696' failures='2'>
...
  <testsuite name='HotelSearchTests.TVSignUpTeaserViewModelSpec' tests='8' failures='2'>
    <testcase classname='HotelSearchTests.TVSignUpTeaserViewModelSpec' name='TVSignUpTeaserViewModelSpec___showSignUpWithEmailCommand___execute__sends_a__RACUnit__as_a_trigger_for_the_subscriber_and_tracks_correctly'>
      <failure message='Unexpected exception raised: ClientIdentifier must be set.'>Carthage/Checkouts/Nimble/Sources/Nimble/DSL+Wait.swift:61</failure>
    </testcase>
    <testcase classname='HotelSearchTests.TVSignUpTeaserViewModelSpec' name='TVSignUpTeaserViewModelSpec___showSignUpWithEmailCommand___execute__sends_a__RACUnit__as_a_trigger_for_the_subscriber_and_tracks_correctly'>
      <failure message='failed - Expectation &lt;(2851, &quot;0&quot;)&gt; not fulfilled'>HotelSearchTests/View Models/TVSignUpTeaserViewModelSpec.swift:63</failure>
    </testcase>
    <testcase classname='HotelSearchTests.TVSignUpTeaserViewModelSpec' name='TVSignUpTeaserViewModelSpec___switchToLogInCommand___execute__sends_a_tuple_and_tracks_correctly' time='0.046'/>
    ...
  </testsuite>
...
</testsuites>
```

I get following in the console:

```
10:56:42.506 INFO: Sensor SwiftSquidSensor (done) | time=666ms
10:56:42.506 INFO: Sensor Swift SwiftSurefireSensor
10:56:42.506 INFO: parsing sonar-reports
10:56:42.779 INFO: ------------------------------------------------------------------------
10:56:42.779 INFO: EXECUTION FAILURE
10:56:42.779 INFO: ------------------------------------------------------------------------
10:56:42.779 INFO: Total time: 13.484s
10:56:42.868 INFO: Final Memory: 44M/280M
10:56:42.868 INFO: ------------------------------------------------------------------------
10:56:42.868 ERROR: Error during SonarQube Scanner execution
org.sonar.api.utils.XmlParserException: Cannot parse surefire reports
	at org.sonar.plugins.swift.tests.SwiftSurefireParser.parseFiles(SwiftSurefireParser.java:142)
	at org.sonar.plugins.swift.tests.SwiftSurefireParser.collect(SwiftSurefireParser.java:74)
	at org.sonar.plugins.swift.tests.SwiftSurefireSensor.collect(SwiftSurefireSensor.java:87)
	at org.sonar.plugins.swift.tests.SwiftSurefireSensor.analyse(SwiftSurefireSensor.java:81)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.NullPointerException
	at java.text.DecimalFormat.parse(DecimalFormat.java:1997)
	at java.text.NumberFormat.parse(NumberFormat.java:383)
	at org.sonar.api.utils.ParsingUtils.parseNumber(ParsingUtils.java:47)
	at org.sonar.plugins.surefire.TestSuiteParser.getTimeAttributeInMS(TestSuiteParser.java:133)
	at org.sonar.plugins.surefire.TestSuiteParser.getTestCaseDetails(TestSuiteParser.java:105)
	at org.sonar.plugins.surefire.TestSuiteParser.cumulateTestCaseDetails(TestSuiteParser.java:80)
	at org.sonar.plugins.surefire.TestSuiteParser.stream(TestSuiteParser.java:62)
	at org.sonar.api.utils.StaxParser.parse(StaxParser.java:115)
	at org.sonar.api.utils.StaxParser.parse(StaxParser.java:95)
	at org.sonar.api.utils.StaxParser.parse(StaxParser.java:85)
	at org.sonar.plugins.swift.tests.SwiftSurefireParser.parseFiles(SwiftSurefireParser.java:106)
	... 32 more
```

When I remove the node ` <testsuite name='HotelSearchTests.TVSignUpTeaserViewModelSpec' tests='8' failures='2'>` and all its content it just works.

**Comment by zippy1978** [comment]
Hi @haynzz,

I think this is due to xcpretty.
which version of xcpretty did you install ?
We forked xcpretty to fix this kind of bug.

Here is how to install our fork :

```
git clone https://github.com/Backelite/xcpretty.git
cd xcpretty
git checkout fix/duration_of_failed_tests_workaround
gem build xcpretty.gemspec
sudo gem install --both xcpretty-0.2.2.gem
```

**Comment by velthune** [comment]
+1

**Comment by defio** [comment]
+1

**Comment by IaroslavTernovyi** [comment]
+1

**Comment by mathieuboniface** [comment]
+1

**Comment by samratBasra** [comment]
+1

**Comment by orj** [comment]
Can we get this fixed in xcpretty upstream?  Having to use a custom fork of xcpretty is really annoying.

**Comment by pbernery** [comment]
A PR has been pushed on February 2016! https://github.com/supermarin/xcpretty/pull/204
Answer from the maintainer in December 2016: this should be fixed in 0.3. 
Still waiting for this version...

**Comment by gretzki** [comment]
Actually, all that is required is a null-Check in SurefireParser.java to fix this.
Did the same for the ObjC project a while ago https://github.com/Backelite/sonar-objective-c/pull/36

**Comment by aelam** [comment]
I get the same problem that Im using xcpretty 0.3
