### ISSUE TITLE
LizardSensor Plugin not compatible with SonarQube 5.3

### ISSUE THREAD

**Issue by gretzki** [Backelite/sonar-swift#7]
When executing sonar-runner the following error occurs:

`ERROR: Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
	at org.sonar.runner.api.Runner.execute(Runner.java:100)
	at org.sonar.runner.Main.executeTask(Main.java:70)
	at org.sonar.runner.Main.execute(Main.java:59)
	at org.sonar.runner.Main.main(Main.java:53)
Caused by: java.lang.NoSuchMethodError: org.sonar.api.resources.Project.getFileSystem()Lorg/sonar/api/resources/ProjectFileSystem;
	at org.sonar.plugins.swift.complexity.LizardSensor.analyse(LizardSensor.java:58)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:98)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:185)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:243)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:238)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:228)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
	... 9 more
`

The interesting line is `Caused by: java.lang.NoSuchMethodError: org.sonar.api.resources.Project.getFileSystem()Lorg/sonar/api/resources/ProjectFileSystem; at org.sonar.plugins.swift.complexity.LizardSensor.analyse(LizardSensor.java:58)`
So I guess LizardSensor is not compatible with the latest SonarQube 5.3 API.
Which SonarQube is this release tested with, I can't find any information on this.

Cheers,
Chris

**Comment by akshaysyaduvanshi** [comment]
This release is tested with SonarQube Version 5.1.1.

**Comment by zippy1978** [comment]
Hi,

I just fixed the issue, the fix is pushed on develop branch.
