### ISSUE TITLE
SwiftLint and Tailor reports are not reported on web view

### ISSUE THREAD

**Issue by grajan** [Backelite/sonar-swift#83]
When I am running run-sonar-swift.sh from my project, the following reports are generated inside the sonar-reports folder.

> SwiftCan-tailor.txt
> lizard-report.xml
> TEST-report.xml
> xcodebuild.log
> SwiftCan-swiftlint.txt
> coverage.xml

My sonar-properties file is as follows

> sonar.projectName=$JOB_NAME
> sonar.projectVersion=1.0
> sonar.language=swift
> sonar.sources=${PROJECT}
> sonar.tests=${PROJECT}Tests
> sonar.swift.simulator=platform=iOS Simulator,name=iPhone 6,OS=10.2
> sonar.swift.project=${PROJECT}.xcodeproj
> sonar.swift.workspace=${WORKSPACE}.xcworkspace
> sonar.swift.appScheme=$SCHEME
> sonar.sourceEncoding=UTF-8
> sonar.junit.reportsPath=sonar-reports/
> sonar.swift.lizard.report=sonar-reports/lizard-report.xml
> sonar.swift.coverage.reportPattern=sonar-reports/coverage*.xml
> sonar.swift.swiftlint.report=sonar-reports/*swiftlint.txt
> sonar.swift.tailor.report=sonar-reports/*tailor.txt
> sonar.swift.excludedPathsFromCoverage=.*Tests.*
> sonar.swift.tailor.config=--max-line-length=100 --max-file-length=500 --max-name-length=40 --max-name-length=40 --min-name-length=4

In sonarQube 6.3 only the code coverage was displayed. Then when I downgraded to sonarQube 6.1, I can also see Code Smells, but nothing more. 

Clearly, the bug reports are being generated, but for some reason not uploaded. Any ideas?

**Comment by jakubgert** [comment]
I have same issue.
Code Smells have fallen to 0 after update SonarQube from 6.3 to Version 6.3.1 (build 21392).

**Comment by Mindbowser** [comment]
Same issue here? Any idea?

**Comment by grajan** [comment]
I thought I was the only one.. didn't find any solution so far :(

**Comment by Mindbowser** [comment]
I guess Quality Profile 'swift' dont have any bugs listed, I can see 0, that might be the reason?

<img width="1251" alt="screen shot 2017-06-20 at 1 19 32 pm" src="https://user-images.githubusercontent.com/1574260/27322281-2ed9347e-55bb-11e7-87d9-1cd97008739a.png">

**Comment by grajan** [comment]
For me the report is generated locally with all the issues, but its just not getting uploaded

**Comment by Mindbowser** [comment]
I am also able to see reports locally but my guess is that if Quality profile dont have that issue listed under bugs how it will show it on web?

**Comment by Mindbowser** [comment]
@pbernery any thoughts what can be wrong? @grajan any luck at your end?

**Comment by pbernery** [comment]
Did you have a look at the output of Sonar Scanner ? There may be some clue about why the reports are not uploaded.

**Comment by Mindbowser** [comment]
I did, nothing found there,
`$ swiftlint lint > sonar-reports/swiftlint.txt
[15:38:36]: ▸ Linting Swift files in current working directory
[15:38:36]: ▸ Linting 'AppDelegate.swift' (1/8)
[15:38:36]: ▸ Linting 'Constant.swift' (2/8)
[15:38:36]: ▸ Linting 'Extension.swift' (3/8)
[15:38:36]: ▸ Linting 'HomeViewController.swift' (4/8)
[15:38:36]: ▸ Linting 'ProfileViewController.swift' (5/8)
[15:38:36]: ▸ Linting 'RegistrationViewController.swift' (6/8)
[15:38:36]: ▸ Linting 'SharedClass.swift' (7/8)
[15:38:36]: ▸ Linting 'TabBarViewController.swift' (8/8)
[15:38:36]: ▸ Done linting! Found 234 violations, 11 serious in 8 files.
[15:38:36]: 
[15:38:36]: SwiftLint finished with exit code 2, which would normally fail the build.
[15:38:36]: fastlane will continue because the `ignore_exit_status` option was used! 🙈
[15:38:36]: 
[15:38:36]: -------------------
[15:38:36]: --- Step: sonar ---
[15:38:36]: -------------------
[15:38:37]: ▸ INFO: Scanner configuration file: NONE
[15:38:37]: ▸ INFO: Project root configuration file: /Users/Pravin/Desktop/LifeList/sonar-project.properties
[15:38:37]: ▸ INFO: SonarQube Scanner 3.0.3.778
[15:38:37]: ▸ INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
[15:38:37]: ▸ INFO: Mac OS X 10.12.5 x86_64
[15:38:38]: ▸ INFO: User cache: /Users/Pravin/.sonar/cache
[15:38:45]: ▸ INFO: Load global settings
[15:38:47]: ▸ INFO: Load global settings (done) | time=1601ms
[15:38:47]: ▸ INFO: User cache: /Users/Pravin/.sonar/cache
[15:38:47]: ▸ INFO: Load plugins index
[15:38:48]: ▸ INFO: Load plugins index (done) | time=287ms
[15:38:48]: ▸ INFO: SonarQube server 6.3.0
[15:38:48]: ▸ INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
[15:38:54]: ▸ INFO: Process project properties
[15:38:54]: ▸ INFO: Load project repositories
[15:38:54]: ▸ INFO: Load project repositories (done) | time=388ms
[15:38:54]: ▸ INFO: Load quality profiles
[15:38:55]: ▸ INFO: Load quality profiles (done) | time=373ms
[15:38:55]: ▸ INFO: Load active rules
[15:38:58]: ▸ INFO: Load active rules (done) | time=3287ms
[15:38:58]: ▸ INFO: Load metrics repository
[15:38:58]: ▸ INFO: Load metrics repository (done) | time=355ms
[15:38:58]: ▸ WARN: SCM provider autodetection failed. No SCM provider claims to support this project. Please use sonar.scm.provider to define SCM of your project.
[15:38:58]: ▸ INFO: Publish mode
[15:38:58]: ▸ INFO: Project key: LifeList-iOS
[15:38:58]: ▸ INFO: -------------  Scan LifeList-iOS
[15:38:59]: ▸ INFO: Excluded sources for coverage:
[15:38:59]: ▸ INFO:   file:**/generated-sources/**
[15:38:59]: ▸ INFO:   file:**/generated/**
[15:38:59]: ▸ INFO: Load server rules
[15:39:00]: ▸ INFO: Load server rules (done) | time=1120ms
[15:39:01]: ▸ INFO: Initializer GenericCoverageSensor
[15:39:01]: ▸ INFO: Initializer GenericCoverageSensor (done) | time=0ms
[15:39:01]: ▸ INFO: Base dir: /Users/Pravin/Desktop/LifeList
[15:39:01]: ▸ INFO: Working dir: /Users/Pravin/Desktop/LifeList/.scannerwork
[15:39:01]: ▸ INFO: Source paths: LifeList
[15:39:01]: ▸ INFO: Source encoding: UTF-8, default locale: en_US
[15:39:01]: ▸ INFO: Index files
[15:39:01]: ▸ INFO: Excluded sources:
[15:39:01]: ▸ INFO:   **/generated-sources/**
[15:39:01]: ▸ INFO:   **/assets/**/*
[15:39:01]: ▸ INFO:   **/vendor/**/*
[15:39:01]: ▸ INFO:   **/generated-sources/**/*
[15:39:01]: ▸ INFO:   **/plugins/**/*
[15:39:01]: ▸ INFO:   **/nbiDocs/**/*
[15:39:01]: ▸ INFO: 266 files indexed
[15:39:01]: ▸ INFO: 0 files ignored because of inclusion/exclusion patterns
[15:39:01]: ▸ INFO: Quality profile for swift: SwiftLint
[15:39:02]: ▸ INFO: Sensor org.sonar.plugins.swift.issues.swiftlint.SwiftLintSensor [backelitesonarswiftplugin]
[15:39:02]: ▸ INFO: Processing SwiftLint report sonar-reports/swiftlint.txt
[15:39:02]: ▸ INFO: Sensor org.sonar.plugins.swift.issues.swiftlint.SwiftLintSensor [backelitesonarswiftplugin] (done) | time=269ms
[15:39:02]: ▸ INFO: Sensor org.sonar.plugins.swift.issues.tailor.TailorSensor [backelitesonarswiftplugin]
[15:39:02]: ▸ INFO: Sensor org.sonar.plugins.swift.issues.tailor.TailorSensor [backelitesonarswiftplugin] (done) | time=3ms
[15:39:02]: ▸ INFO: Sensor SwiftSquidSensor [backelitesonarswiftplugin]
[15:39:03]: ▸ WARN: Metric 'lines' is an internal metric computed by SonarQube. Provided value is ignored.
[15:39:03]: ▸ INFO: Sensor SwiftSquidSensor [backelitesonarswiftplugin] (done) | time=268ms
[15:39:03]: ▸ INFO: Sensor Swift SwiftSurefireSensor [backelitesonarswiftplugin]
[15:39:03]: ▸ INFO: parsing sonar-reports
[15:39:03]: ▸ WARN: file for test class LifeListTests not found
[15:39:03]: ▸ INFO: Sensor Swift SwiftSurefireSensor [backelitesonarswiftplugin] (done) | time=179ms
[15:39:03]: ▸ INFO: Sensor org.sonar.plugins.swift.coverage.SwiftCoberturaSensor [backelitesonarswiftplugin]
[15:39:03]: ▸ INFO: Sensor org.sonar.plugins.swift.coverage.SwiftCoberturaSensor [backelitesonarswiftplugin] (done) | time=2ms
[15:39:03]: ▸ INFO: Sensor org.sonar.plugins.swift.complexity.LizardSensor [backelitesonarswiftplugin]
[15:39:03]: ▸ INFO: Processing complexity report
[15:39:03]: ▸ INFO: Saving results of complexity analysis
[15:39:03]: ▸ INFO: Sensor org.sonar.plugins.swift.complexity.LizardSensor [backelitesonarswiftplugin] (done) | time=141ms
[15:39:03]: ▸ INFO: Sensor Embedded CSS Analyzer Sensor [css]
[15:39:03]: ▸ INFO: 0 source files to be analyzed
[15:39:03]: ▸ INFO: Sensor Embedded CSS Analyzer Sensor [css] (done) | time=193ms
[15:39:03]: ▸ INFO: 0/0 source files have been analyzed
[15:39:03]: ▸ INFO: Sensor Coverage Report Import [csharp]
[15:39:03]: ▸ INFO: Sensor Coverage Report Import [csharp] (done) | time=15ms
[15:39:03]: ▸ INFO: Sensor Coverage Report Import [csharp]
[15:39:03]: ▸ INFO: Sensor Coverage Report Import [csharp] (done) | time=0ms
[15:39:03]: ▸ INFO: Sensor Unit Test Results Import [csharp]
[15:39:03]: ▸ INFO: Sensor Unit Test Results Import [csharp] (done) | time=1ms
[15:39:03]: ▸ INFO: Sensor SonarJavaXmlFileSensor [java]
[15:39:03]: ▸ INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=2ms
[15:39:03]: ▸ INFO: Sensor Zero Coverage Sensor
[15:39:03]: ▸ INFO: Sensor Zero Coverage Sensor (done) | time=111ms
[15:39:03]: ▸ INFO: Sensor Code Colorizer Sensor
[15:39:04]: ▸ INFO: Sensor Code Colorizer Sensor (done) | time=122ms
[15:39:04]: ▸ INFO: Sensor CPD Block Indexer
[15:39:04]: ▸ INFO: org.sonar.scanner.cpd.deprecated.DefaultCpdBlockIndexer@7d66e544 is used for swift
[15:39:04]: ▸ INFO: Sensor CPD Block Indexer (done) | time=31ms
[15:39:04]: ▸ INFO: No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
[15:39:04]: ▸ INFO: Calculating CPD for 7 files
[15:39:04]: ▸ INFO: CPD calculation finished
[15:39:04]: ▸ INFO: Analysis report generated in 193ms, dir size=97 KB
[15:39:04]: ▸ INFO: Analysis reports compressed in 51ms, zip size=33 KB
[15:39:05]: ▸ INFO: Analysis report uploaded in 1034ms
[15:39:05]: ▸ INFO: ANALYSIS SUCCESSFUL,`

**Comment by grajan** [comment]
@Mindbowser nope. While execution, sonar is clearly logging the issues. Then it says the process is successful, but the reports are not uploaded. :(

**Comment by grajan** [comment]
@pbernery On executing the script, it just logs
"Done linting! Found 1124 violations. 37 serious in 22 files.
 Running Tailor..........Running Lizard...Running SonarQube using SonarQube Runner..."
And then I get a report in the sonar server with only the Code coverage report. 0 bugs and vulnerabilities..

**Comment by Mindbowser** [comment]
Any luck?

**Comment by grajan** [comment]
Nope

**Comment by Mindbowser** [comment]
@pbernery Any thoughts?

**Comment by pbernery** [comment]
I guess the plugin is not ready for these versions of Sonar. We are currently using 5.6 and have not tested the plugin on Sonar 6.2 and +.

I invite you to look at the plugin source code and try to compile it with SonarQube 6.2. There should be warnings or even compile errors indicating precisely which APIs changed.

**Comment by Mindbowser** [comment]
@pbernery is there any plans to upgrade it?

**Comment by Mindbowser** [comment]
I tried compiling plugin against the sonar version 6.3, many changes has been made and I was finally able to compile, but when deployed under sonar I am getting following error on server,

> java.lang.IllegalStateException: Fail to load plugin Swift (Backelite) [backelitesonarswiftplugin]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:73)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:527)
	at org.sonar.server.platform.Platform.start(Platform.java:203)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:177)
	at org.sonar.server.platform.Platform.doStart(Platform.java:100)
	at org.sonar.server.platform.Platform.doStart(Platform.java:79)
	at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:45)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
	at org.sonar.plugins.swift.SwiftPlugin.getExtensions(SwiftPlugin.java:90)
	at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:63)
	... 15 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)

**Comment by Mindbowser** [comment]
@pbernery after this I tried using Plugin interface instead SonarPlugin class, but now it is giving error about apache IOUtils class not found, not sure if you faced such issues earlier. FYI, when running mvn on eclipse, final step is failing 

`[ERROR] Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.13:check (enforce-java-api-compatibility) on project backelite-sonar-swift-plugin: Execution enforce-java-api-compatibility of goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.13:check failed. IllegalArgumentException -> [Help 1]
`

**Comment by pbernery** [comment]
Hey @Mindbowser. No, I never faced this issue. Maybe @zippy1978 had?

Otherwise, I'll try to have a look on the plugin during August (I can't before unfortunately).

**Comment by Mindbowser** [comment]
@pbernery  to save your time in compiling and updating libraries, should I add zip file here and then you can spend a little time to check the issue? Let me know if that works. I am using Eclipse FYI.

**Comment by Mindbowser** [comment]
@pbernery  @zippy1978  any idea about below warnings? Thats why I am getting class not found when I add plugin under Sonar

`[WARNING] com.google.code.findbugs:jsr305:jar:1.3.9:compile is provided by SonarQube plugin API and will not be packaged in your plugin
[WARNING] commons-io:commons-io:jar:2.4:compile is provided by SonarQube plugin API and will not be packaged in your plugin
[WARNING] org.slf4j:slf4j-api:jar:1.5.6:compile is provided by SonarQube plugin API and will not be packaged in your plugin
[WARNING] com.google.guava:guava:jar:10.0.1:compile is provided by SonarQube plugin API and will not be packaged in your plugin
[WARNING] org.codehaus.sonar:sonar-colorizer:jar:3.7:compile is provided by SonarQube plugin API and will not be packaged in your plugin
[WARNING] org.codehaus.sonar:sonar-channel:jar:3.7:compile is provided by SonarQube plugin API and will not be packaged in your plugin`

**Comment by Mindbowser** [comment]
@pbernery did you got chance to check the issue?

**Comment by pbernery** [comment]
Hey @Mindbowser, I just came back. I'll try to have a look this week on the different issues. Hopefully, we'll make it work.

**Comment by jakubgert** [comment]
Hi all,
I found solution for my issue (https://github.com/Backelite/sonar-swift/issues/83#issuecomment-308704593)
For some reason all rules in QualityProfiles for Swift has been switched to OFF during migration. After reactivating rules, everything started to work as it should.

**Comment by Mindbowser** [comment]
@jakubgert I have all rules activated but only code smells are getting reflected and all others things are showing 0

**Comment by zippy1978** [comment]
Hi @Mindbowser, the fact that you only get code smells probably comes from an API deprecation. We will try to fix it in a next release.

**Comment by Mindbowser** [comment]
Thanks. I see many issues you fixed in no time 😀, look forward to this one as well

**Comment by thiagoaos** [comment]
Some news in this issue? I cant upload Tailor report to Sonar 6.2. I'm using Tailor in linux enviroment.

**Comment by Mindbowser** [comment]
Yes I am also waiting badly.

**Comment by Mindbowser** [comment]
Any updates on this issue? I just installed latest Sonar version 6.7.1.35068 LTS, still no bugs are showing up. Any idea?

**Comment by AhmedAskar** [comment]
It gives me 
Done linting! Found 5880 violations, 418 serious in 183 files.
Running Tailor...........................Skipping Lizard (not installed!)
Running SonarQube using SonarQube Runner..WARN: Metric 'lines' is an internal metric computed by SonarQube. Provided value is ignored.
ERROR: Lizard Report not found /Users/ahmedaskar/Askar/omni_chan_ios_1/sonar-reports/lizard-report.xml
java.io.FileNotFoundException: /Users/ahmedaskar/Askar/omni_chan_ios_1/sonar-reports/lizard-report.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:805)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.sonar.plugins.swift.complexity.LizardReportParser.parseReport(LizardReportParser.java:62)
	at org.sonar.plugins.swift.complexity.LizardSensor.parseReportsIn(LizardSensor.java:66)
	at org.sonar.plugins.swift.complexity.LizardSensor.analyse(LizardSensor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

WARN: Missing blame information for the following files:
WARN:   * OmniChannel/Application/AppDelegate.swift
WARN:   * OmniChannel/Network/OperationManager/RequestOperationManager.swift
WARN:   * OmniChannel/Utilities/OmniConstants.swift
WARN:   * OmniChannel/View/ViewController/BaseViewController.swift
WARN:   * OmniChannel/View/ViewController/LoginController.swift
WARN:   * OmniChannel/View/ViewController/RegistrationViewController.swift
WARN:   * OmniChannelTests/AdminControllerTestCase.swift
WARN:   * OmniChannelTests/SotryRendererModelTestCase.swift
WARN:   * OmniChannelTests/StoryRendererVCTestCase.swift
WARN: This may lead to missing/broken features in SonarQube

**Comment by greenmood** [comment]
What's the current status? Also where i can find supported Sonar versions?

**Comment by gaelfoppolo** [comment]
Do you still face this issue with the current version of the plugin?
Can you provide a project sample to reproduce the issue?

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
