### ISSUE TITLE
Support with working Bitbucket Pipeline

### ISSUE THREAD

**Issue by Mindbowser** [Backelite/sonar-swift#91]
I have latest SonarQube installed(opensource SonarSource), I am also using BitbucketPipeline so that on every commit we get report. For all other projects it is working fine and SonarQube automatically detects its language and apply proper profile, but for swift projects even adding Swift as default profile nothing is happening, as I am not sure Prerequisites mentioned are only for xcode environment right? I have not installed anything on my sonar server from mentioned Prerequisites, please let me know if anything is missing or where I can check logs.

**Comment by Mindbowser** [comment]
I have more logs for you, seems like that issue is with lizard, I installed it but error is still there,

+ ./$MB_ANALYSIS_SERVER_PACKAGE_NAME/bin/sonar-scanner -Dsonar.host.url=$MB_ANALYSIS_SERVER_URL -Dsonar.login=$MB_ANALYSIS_SERVER_KEY -Dsonar.branch=$BITBUCKET_BRANCH -Dsonar.sources=$BITBUCKET_CLONE_DIR/. -Dsonar.sourceEncoding=UTF-8 -Dsonar.analysis.mode=publish -Dsonar.projectKey=Vulcan-sonar-test-iOS -Dsonar.projectName=Vulcan-sonar-test-iOS
INFO: Scanner configuration file: /opt/atlassian/pipelines/agent/build/sonar-scanner-3.0.0.702/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarQube Scanner 3.0.0.702
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Linux 4.9.24-coreos amd64
INFO: User cache: /root/.sonar/cache
INFO: Load global settings
INFO: Load global settings (done) | time=682ms
INFO: User cache: /root/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=96ms
INFO: Download sonar-csharp-plugin-5.7.0.612.jar
INFO: Download sonar-css-plugin-3.1.jar
INFO: Download sonar-java-plugin-4.7.1.9272.jar
INFO: Download sonar-web-plugin-2.5.0.476.jar
INFO: Download sonar-scm-git-plugin-1.2.jar
INFO: Download sonar-android-plugin-1.1.jar
INFO: Download sonar-auth-bitbucket-plugin-1.0.jar
INFO: Download backelite-sonar-swift-plugin-0.3.4.jar
INFO: Download sonar-scm-svn-plugin-1.4.0.522.jar
INFO: Download sonar-city-model-plugin-3.4.1.jar
INFO: Download sonar-javascript-plugin-2.21.0.4409.jar
INFO: Download qualinsight-sonarqube-badges-3.0.1.jar
INFO: SonarQube server 6.3.0
INFO: Default locale: "en_US", source code encoding: "UTF-8"
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=192ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=120ms
INFO: Load active rules
INFO: Load active rules (done) | time=1416ms
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=157ms
INFO: Publish mode
INFO: Project key: Vulcan-sonar-test-iOS
INFO: Branch key: pravin-sonar-check
INFO: -------------  Scan Vulcan-sonar-test-iOS
INFO: Excluded sources for coverage: 
INFO:   file:**/generated-sources/**
INFO:   file:**/generated/**
INFO: Load server rules
INFO: Load server rules (done) | time=349ms
INFO: Initializer GenericCoverageSensor
INFO: Initializer GenericCoverageSensor (done) | time=1ms
INFO: Base dir: /opt/atlassian/pipelines/agent/build
INFO: Working dir: /opt/atlassian/pipelines/agent/build/.scannerwork
INFO: Source paths: .
INFO: Source encoding: UTF-8, default locale: en_US
INFO: Index files
INFO: Excluded sources: 
INFO:   **/generated-sources/**
INFO:   **/assets/**/*
INFO:   **/vendor/**/*
INFO:   **/generated-sources/**/*
INFO:   **/plugins/**/*
INFO:   **/nbiDocs/**/*
INFO: 887 files indexed
INFO: 0 files ignored because of inclusion/exclusion patterns
INFO: Quality profile for swift: Swift
INFO: Sensor org.sonar.plugins.swift.issues.swiftlint.SwiftLintSensor [backelitesonarswiftplugin]
INFO: Sensor org.sonar.plugins.swift.issues.swiftlint.SwiftLintSensor [backelitesonarswiftplugin] (done) | time=208ms
INFO: Sensor org.sonar.plugins.swift.issues.tailor.TailorSensor [backelitesonarswiftplugin]
INFO: Sensor org.sonar.plugins.swift.issues.tailor.TailorSensor [backelitesonarswiftplugin] (done) | time=0ms
INFO: Sensor SwiftSquidSensor [backelitesonarswiftplugin]
WARN: Metric 'lines' is an internal metric computed by SonarQube. Provided value is ignored.
INFO: Sensor SwiftSquidSensor [backelitesonarswiftplugin] (done) | time=226ms
INFO: Sensor Swift SwiftSurefireSensor [backelitesonarswiftplugin]
INFO: parsing sonar-reports
INFO: Sensor Swift SwiftSurefireSensor [backelitesonarswiftplugin] (done) | time=2ms
INFO: Sensor org.sonar.plugins.swift.coverage.SwiftCoberturaSensor [backelitesonarswiftplugin]
INFO: Sensor org.sonar.plugins.swift.coverage.SwiftCoberturaSensor [backelitesonarswiftplugin] (done) | time=0ms
INFO: Sensor org.sonar.plugins.swift.complexity.LizardSensor [backelitesonarswiftplugin]
INFO: Processing complexity report 
ERROR: Lizard Report not found /opt/atlassian/pipelines/agent/build/sonar-reports/lizard-report.xml
java.io.FileNotFoundException: /opt/atlassian/pipelines/agent/build/sonar-reports/lizard-report.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:805)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.sonar.plugins.swift.complexity.LizardReportParser.parseReport(LizardReportParser.java:65)
	at org.sonar.plugins.swift.complexity.LizardSensor.parseReportsIn(LizardSensor.java:69)
	at org.sonar.plugins.swift.complexity.LizardSensor.analyse(LizardSensor.java:60)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:74)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

INFO: Saving results of complexity analysis
INFO: Sensor org.sonar.plugins.swift.complexity.LizardSensor [backelitesonarswiftplugin] (done) | time=10ms
INFO: Sensor Embedded CSS Analyzer Sensor [css]
INFO: 0 source files to be analyzed
INFO: 0/0 source files have been analyzed
INFO: Sensor Embedded CSS Analyzer Sensor [css] (done) | time=164ms
INFO: Sensor Coverage Report Import [csharp]
INFO: Sensor Coverage Report Import [csharp] (done) | time=0ms
INFO: Sensor Coverage Report Import [csharp]
INFO: Sensor Coverage Report Import [csharp] (done) | time=0ms
INFO: Sensor Unit Test Results Import [csharp]
INFO: Sensor Unit Test Results Import [csharp] (done) | time=0ms
INFO: Sensor XmlFileSensor [java]
INFO: Sensor XmlFileSensor [java] (done) | time=20ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=225ms
INFO: Sensor Code Colorizer Sensor
INFO: Sensor Code Colorizer Sensor (done) | time=303ms
INFO: Sensor CPD Block Indexer
INFO: org.sonar.scanner.cpd.deprecated.DefaultCpdBlockIndexer@4f664bee is used for swift
INFO: Sensor CPD Block Indexer (done) | time=97ms
INFO: Calculating CPD for 22 files
INFO: CPD calculation finished
INFO: Analysis report generated in 255ms, dir size=107 KB
INFO: Analysis reports compressed in 65ms, zip size=58 KB
INFO: Analysis report uploaded in 343ms

**Comment by pbernery** [comment]
The reports indicates there is not lizard report found (should be at /opt/atlassian/pipelines/agent/build/sonar-reports/lizard-report.xml).
Have you the tool correctly installed?
Is it correctly running? Try to run it by yourself to make sure it is running correctly.

**Comment by gaelfoppolo** [comment]
What is the status on this issue @Mindbowser?
Without any response, I will close this issue.

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
